"""
生成CEFR词表JSON文件

基于多个免费来源整合：
- Oxford 3000 (A1-B2)
- Academic Word List (AWL)
- 常见CEFR分级词表

输出格式：[{"word": "...", "level": "A1|A2|B1|B2|C1|C2"}, ...]
冲突处理：同一单词取最高等级
"""

import json
import os

# Oxford 3000 核心词（按CEFR等级分组）
# 来源：Oxford Learner's Dictionaries (免费公开部分)
OXFORD_A1 = [
    'a', 'about', 'above', 'across', 'act', 'action', 'actually', 'add',
    'afraid', 'after', 'afternoon', 'again', 'age', 'ago', 'agree', 'air',
    'all', 'allow', 'almost', 'alone', 'along', 'already', 'also', 'always',
    'amazing', 'an', 'and', 'angry', 'animal', 'another', 'answer', 'any',
    'anyone', 'anything', 'anywhere', 'appear', 'apple', 'area', 'arm',
    'around', 'arrive', 'art', 'as', 'ask', 'at', 'attack', 'aunt',
    'autumn', 'away', 'baby', 'back', 'bad', 'bag', 'ball', 'bank',
    'base', 'bath', 'be', 'beach', 'bear', 'beautiful', 'because', 'become',
    'bed', 'bedroom', 'beer', 'before', 'begin', 'behind', 'believe',
    'below', 'beside', 'best', 'better', 'between', 'big', 'bike',
    'bill', 'bird', 'birthday', 'bit', 'black', 'block', 'blood', 'blow',
    'blue', 'board', 'boat', 'body', 'bone', 'book', 'border', 'born',
    'both', 'bottle', 'bottom', 'bowl', 'box', 'boy', 'brain', 'branch',
    'bread', 'break', 'breakfast', 'bridge', 'bright', 'bring', 'brother',
    'brown', 'budget', 'build', 'building', 'burn', 'bus', 'business',
    'busy', 'but', 'buy', 'by', 'cafe', 'call', 'can', 'capital', 'car',
    'card', 'care', 'carefully', 'carry', 'case', 'cat', 'catch', 'cause',
    'central', 'centre', 'century', 'certainly', 'chair', 'chairman',
    'chance', 'change', 'channel', 'chapter', 'charge', 'cheap', 'check',
    'child', 'choice', 'choose', 'church', 'cinema', 'city', 'claim',
    'class', 'clean', 'clear', 'clearly', 'close', 'clothes', 'club',
    'coach', 'coffee', 'cold', 'college', 'colour', 'come', 'common',
    'community', 'company', 'compare', 'computer', 'concern', 'condition',
    'conference', 'consider', 'contact', 'contain', 'content', 'context',
    'continue', 'control', 'convince', 'cook', 'cool', 'copy', 'corner',
    'correct', 'cost', 'could', 'council', 'count', 'country', 'couple',
    'course', 'court', 'cover', 'create', 'crime', 'cross', 'cup',
    'current', 'customer', 'cut', 'dad', 'damage', 'danger', 'dangerous',
    'dark', 'daughter', 'day', 'dead', 'deal', 'dear', 'death', 'debate',
    'decide', 'decision', 'deep', 'definitely', 'degree', 'deliver',
    'demand', 'department', 'depend', 'describe', 'design', 'desk',
    'detail', 'develop', 'development', 'die', 'difference', 'different',
    'difficult', 'dinner', 'direct', 'direction', 'director', 'discover',
    'discuss', 'discussion', 'disease', 'doctor', 'document', 'dog', 'door',
    'double', 'doubt', 'down', 'draw', 'dream', 'dress', 'drink', 'drive',
    'drop', 'dry', 'due', 'during', 'each', 'ear', 'early', 'east',
    'easy', 'eat', 'economy', 'edge', 'education', 'effect', 'effort',
    'eight', 'either', 'else', 'employee', 'end', 'energy', 'enjoy',
    'enough', 'enter', 'environment', 'especially', 'euro', 'even',
    'evening', 'event', 'ever', 'every', 'everybody', 'everyone',
    'everything', 'everywhere', 'evidence', 'exactly', 'exam', 'example',
    'excellent', 'except', 'exchange', 'executive', 'exercise', 'exist',
    'expect', 'experience', 'explain', 'express', 'extra', 'eye', 'face',
    'fact', 'fail', 'fair', 'fall', 'family', 'far', 'fast', 'father',
    'favourite', 'fear', 'feature', 'feed', 'feel', 'few', 'field',
    'fight', 'fill', 'film', 'final', 'finally', 'financial', 'find',
    'fine', 'finger', 'finish', 'fire', 'first', 'fish', 'fit', 'five',
    'flat', 'flight', 'floor', 'fly', 'follow', 'food', 'foot', 'football',
    'for', 'force', 'foreign', 'forest', 'forget', 'form', 'former',
    'forward', 'four', 'free', 'fresh', 'friend', 'front', 'fruit',
    'full', 'fun', 'fund', 'future', 'game', 'garden', 'gate', 'general',
    'generation', 'get', 'girl', 'give', 'glass', 'go', 'god', 'gold',
    'good', 'government', 'great', 'green', 'grey', 'ground', 'group',
    'grow', 'growth', 'guess', 'gun', 'guy', 'hair', 'half', 'hall',
    'hand', 'hang', 'happen', 'happy', 'hard', 'hat', 'hate', 'have',
    'he', 'head', 'health', 'hear', 'heart', 'heat', 'heavy', 'help',
    'her', 'here', 'herself', 'high', 'him', 'himself', 'his', 'historical',
    'history', 'hit', 'hold', 'hole', 'holiday', 'home', 'hope', 'horse',
    'hospital', 'hot', 'hotel', 'hour', 'house', 'how', 'however', 'huge',
    'human', 'hundred', 'husband', 'idea', 'identify', 'if', 'image',
    'imagine', 'important', 'improve', 'in', 'include', 'including',
    'increase', 'indeed', 'indicate', 'individual', 'industry', 'information',
    'inside', 'instead', 'institution', 'interest', 'interesting',
    'international', 'interview', 'into', 'introduce', 'investment',
    'involve', 'issue', 'it', 'item', 'its', 'itself', 'job', 'join',
    'just', 'keep', 'key', 'kid', 'kill', 'kind', 'king', 'kitchen',
    'know', 'knowledge', 'land', 'language', 'large', 'last', 'late',
    'later', 'laugh', 'law', 'lay', 'lead', 'leader', 'learn', 'least',
    'leave', 'left', 'leg', 'legal', 'less', 'let', 'letter', 'level',
    'lie', 'life', 'lift', 'light', 'like', 'likely', 'limit', 'line',
    'link', 'list', 'listen', 'little', 'live', 'local', 'long', 'look',
    'lord', 'lose', 'loss', 'lot', 'love', 'lovely', 'low', 'lunch',
    'machine', 'main', 'major', 'make', 'male', 'man', 'manage',
    'management', 'manager', 'many', 'market', 'marriage', 'matter',
    'may', 'maybe', 'me', 'mean', 'meaning', 'measure', 'media',
    'medical', 'meet', 'meeting', 'member', 'memory', 'mental', 'mention',
    'message', 'method', 'middle', 'might', 'mile', 'military', 'million',
    'mind', 'minute', 'miss', 'mistake', 'model', 'modern', 'moment',
    'money', 'month', 'more', 'morning', 'most', 'mother', 'mouth',
    'move', 'movement', 'movie', 'much', 'music', 'must', 'my', 'myself',
    'name', 'nation', 'national', 'natural', 'nature', 'near', 'nearly',
    'necessary', 'need', 'network', 'never', 'new', 'news', 'newspaper',
    'next', 'nice', 'night', 'no', 'none', 'nor', 'north', 'northern',
    'not', 'note', 'nothing', 'notice', 'now', 'number', 'occur', 'of',
    'off', 'offer', 'office', 'officer', 'official', 'often', 'oh', 'oil',
    'ok', 'old', 'on', 'once', 'one', 'only', 'onto', 'open', 'operate',
    'opportunity', 'option', 'or', 'order', 'ordinary', 'organisation',
    'other', 'otherwise', 'our', 'out', 'outside', 'over', 'own', 'owner',
    'page', 'pain', 'painting', 'pair', 'paper', 'parent', 'park',
    'part', 'particular', 'particularly', 'partner', 'party', 'pass',
    'past', 'path', 'patient', 'pattern', 'pay', 'peace', 'people',
    'per', 'perfect', 'perhaps', 'period', 'person', 'personal', 'phone',
    'physical', 'pick', 'picture', 'piece', 'place', 'plan', 'plant',
    'play', 'player', 'please', 'point', 'police', 'policy', 'political',
    'politics', 'poor', 'popular', 'population', 'position', 'positive',
    'possible', 'power', 'practice', 'prepare', 'present', 'president',
    'pressure', 'pretty', 'prevent', 'price', 'private', 'probably',
    'problem', 'process', 'produce', 'product', 'production', 'professional',
    'program', 'project', 'property', 'protect', 'prove', 'provide',
    'public', 'pull', 'purpose', 'push', 'put', 'quality', 'question',
    'quickly', 'quite', 'race', 'radio', 'raise', 'range', 'rate',
    'rather', 'reach', 'read', 'ready', 'real', 'realise', 'really',
    'reason', 'receive', 'recent', 'recently', 'recognise', 'record',
    'red', 'reduce', 'region', 'relate', 'relationship', 'remember',
    'remove', 'report', 'represent', 'require', 'research', 'resource',
    'respond', 'response', 'rest', 'result', 'return', 'reveal', 'rich',
    'right', 'rise', 'risk', 'road', 'rock', 'role', 'room', 'rule',
    'run', 'safe', 'sale', 'same', 'save', 'say', 'scene', 'school',
    'science', 'scientist', 'score', 'sea', 'season', 'seat', 'second',
    'section', 'security', 'see', 'sell', 'send', 'senior', 'sense',
    'series', 'serious', 'serve', 'service', 'set', 'seven', 'several',
    'shake', 'shall', 'share', 'she', 'shoot', 'shop', 'short', 'shot',
    'should', 'shoulder', 'show', 'side', 'sign', 'significant', 'similar',
    'simple', 'simply', 'since', 'sing', 'single', 'sir', 'sister',
    'sit', 'site', 'situation', 'six', 'size', 'skill', 'skin', 'small',
    'smile', 'so', 'social', 'society', 'soldier', 'some', 'somebody',
    'someone', 'something', 'sometimes', 'son', 'song', 'soon', 'sort',
    'sound', 'source', 'south', 'southern', 'space', 'speak', 'special',
    'specific', 'speech', 'speed', 'sport', 'spring', 'staff', 'stage',
    'stand', 'standard', 'star', 'start', 'state', 'station', 'stay',
    'step', 'still', 'stop', 'story', 'strategy', 'street', 'strong',
    'structure', 'student', 'study', 'stuff', 'style', 'subject',
    'success', 'successful', 'such', 'suddenly', 'suffer', 'suggest',
    'summer', 'support', 'sure', 'surface', 'surprise', 'system',
    'table', 'take', 'talk', 'tax', 'teach', 'teacher', 'team',
    'technology', 'television', 'tell', 'ten', 'tend', 'term', 'test',
    'than', 'thank', 'that', 'the', 'their', 'them', 'themselves',
    'then', 'there', 'therefore', 'these', 'they', 'thing', 'think',
    'third', 'this', 'those', 'though', 'thought', 'thousand', 'threat',
    'three', 'through', 'throughout', 'throw', 'thus', 'time', 'to',
    'today', 'together', 'tomorrow', 'tonight', 'too', 'top', 'total',
    'tough', 'toward', 'town', 'trade', 'traditional', 'training',
    'travel', 'treat', 'treatment', 'tree', 'trial', 'trip', 'trouble',
    'true', 'trust', 'truth', 'try', 'turn', 'tv', 'twice', 'two',
    'type', 'under', 'understand', 'unit', 'until', 'up', 'upon',
    'us', 'use', 'usually', 'value', 'various', 'very', 'victim',
    'view', 'violence', 'visit', 'voice', 'vote', 'wait', 'walk',
    'wall', 'want', 'war', 'watch', 'water', 'way', 'we', 'weapon',
    'wear', 'week', 'weight', 'well', 'west', 'western', 'what',
    'whatever', 'when', 'where', 'whereas', 'whether', 'which', 'while',
    'white', 'who', 'whole', 'whom', 'whose', 'why', 'wide', 'wife',
    'will', 'win', 'wind', 'window', 'wish', 'with', 'within', 'without',
    'woman', 'wonder', 'word', 'work', 'worker', 'world', 'worry',
    'would', 'write', 'writer', 'wrong', 'yeah', 'year', 'yes',
    'yet', 'you', 'young', 'your', 'yourself', 'youth',
]

OXFORD_A2 = [
    'accident', 'adventure', 'advertise', 'advice', 'afford', 'against',
    'agency', 'agent', 'ahead', 'aim', 'alarm', 'alive', 'allow',
    'alongside', 'altogether', 'ambition', 'ancient', 'angle', 'announce',
    'annual', 'anxious', 'anyway', 'apart', 'apartment', 'apologize',
    'appeal', 'application', 'apply', 'appointment', 'approach',
    'appropriate', 'argue', 'arrange', 'arrest', 'arrival', 'aside',
    'associate', 'atmosphere', 'attach', 'attempt', 'attend', 'attention',
    'attitude', 'attract', 'audience', 'authority', 'available', 'average',
    'avoid', 'awake', 'award', 'aware', 'awful', 'background', 'balance',
    'bar', 'base', 'basic', 'basin', 'basis', 'basket', 'bat', 'battle',
    'bay', 'bean', 'beard', 'beat', 'bedroom', 'behalf', 'bell', 'belt',
    'bench', 'bend', 'benefit', 'besides', 'beyond', 'billion', 'birth',
    'bite', 'blame', 'blank', 'blanket', 'bleed', 'blind', 'block',
    'blow', 'bomb', 'bond', 'border', 'bother', 'bottom', 'bowl', 'branch',
    'brand', 'brave', 'breast', 'breath', 'breathe', 'brick', 'brief',
    'bright', 'brilliant', 'broad', 'broadcast', 'brush', 'bug', 'bunch',
    'burden', 'burn', 'burst', 'bury', 'cabin', 'cable', 'calculate',
    'calm', 'camp', 'campaign', 'campus', 'cancel', 'cancer', 'capable',
    'capacity', 'capture', 'carbon', 'career', 'cargo', 'carpet', 'carrot',
    'castle', 'casual', 'catch', 'cattle', 'celebrate', 'cell', 'chain',
    'chair', 'challenge', 'champion', 'chapter', 'character', 'charity',
    'chart', 'chase', 'cheap', 'cheek', 'chemical', 'chest', 'chicken',
    'chief', 'chip', 'chronic', 'circle', 'citizen', 'civil', 'classic',
    'classroom', 'clay', 'click', 'client', 'climate', 'climb', 'cling',
    'clock', 'cloth', 'cloud', 'club', 'clue', 'cluster', 'coast',
    'coat', 'code', 'coin', 'collapse', 'colleague', 'column', 'combine',
    'comfort', 'command', 'comment', 'commission', 'commit', 'committee',
    'communicate', 'comparison', 'compete', 'complaint', 'complex',
    'component', 'concentrate', 'concept', 'conclude', 'conclusion',
    'conduct', 'conference', 'confidence', 'conflict', 'confuse',
    'connect', 'conscious', 'consensus', 'consequence', 'conservative',
    'considerable', 'consist', 'constant', 'construct', 'construction',
    'consultant', 'consumer', 'contact', 'contest', 'context',
    'contract', 'contrast', 'contribute', 'controversial', 'convention',
    'conversation', 'convert', 'convince', 'cooperate', 'cope', 'core',
    'corporate', 'correspond', 'cotton', 'council', 'count', 'county',
    'courage', 'crash', 'crazy', 'cream', 'creative', 'crew', 'crisis',
    'critic', 'critical', 'criticism', 'crop', 'crowd', 'crown', 'crucial',
    'crush', 'crystal', 'cultural', 'currency', 'curriculum', 'curve',
    'customer', 'cycle', 'daily', 'damage', 'dare', 'data', 'database',
    'date', 'deadline', 'deaf', 'deal', 'dear', 'debate', 'debt',
    'decent', 'deck', 'declare', 'decline', 'decorate', 'decrease',
    'define', 'definite', 'definition', 'deliberate', 'delicate',
    'delight', 'deliver', 'delivery', 'demand', 'democracy', 'demonstrate',
    'deny', 'department', 'departure', 'depend', 'deposit', 'depression',
    'derive', 'describe', 'description', 'desert', 'deserve', 'design',
    'designer', 'desire', 'desperate', 'despite', 'destination', 'destroy',
    'detail', 'detect', 'determine', 'device', 'devote', 'diagram',
    'dialogue', 'diamond', 'diary', 'diet', 'dig', 'dimension',
    'direct', 'direction', 'dirt', 'disability', 'disagree', 'disappear',
    'disappoint', 'disaster', 'discipline', 'discount', 'discover',
    'discovery', 'discrimination', 'discuss', 'disease', 'dismiss',
    'display', 'dispute', 'distance', 'distinguish', 'distribute',
    'district', 'divide', 'document', 'domestic', 'dominant', 'dominate',
    'double', 'doubt', 'draft', 'drag', 'drama', 'dramatic', 'draw',
    'drawing', 'dream', 'dress', 'drift', 'drink', 'drive', 'driver',
    'drop', 'drown', 'drug', 'drum', 'dry', 'due', 'dull', 'dump',
    'dust', 'duty', 'dynamic', 'eager', 'earn', 'earth', 'ease',
    'eastern', 'economic', 'economics', 'economy', 'editor', 'educate',
    'effective', 'efficient', 'effort', 'elaborate', 'elderly', 'elect',
    'election', 'electric', 'electronic', 'element', 'eliminate',
    'embrace', 'emerge', 'emergency', 'emission', 'emotion', 'emphasis',
    'empire', 'employ', 'employment', 'enable', 'encounter', 'encourage',
    'enemy', 'engage', 'engine', 'engineering', 'enormous', 'ensure',
    'enterprise', 'entire', 'entirely', 'entrance', 'entry', 'episode',
    'equal', 'equipment', 'era', 'error', 'escape', 'especially',
    'essay', 'essential', 'establish', 'estate', 'estimate', 'evaluate',
    'eventually', 'everyday', 'evidence', 'evil', 'evolution', 'evolve',
    'examination', 'examine', 'excellent', 'exception', 'exchange',
    'exciting', 'exclude', 'excuse', 'execute', 'exercise', 'exhibit',
    'exhibition', 'expand', 'expansion', 'expect', 'expense', 'experiment',
    'expert', 'explain', 'explanation', 'explicit', 'explore', 'explosion',
    'export', 'expose', 'exposure', 'extend', 'extension', 'extensive',
    'extent', 'external', 'extra', 'extraordinary', 'extreme', 'fabric',
    'facility', 'factor', 'faculty', 'failure', 'faith', 'fame',
    'familiar', 'fancy', 'fantasy', 'fashion', 'fate', 'fault',
    'favour', 'fear', 'feature', 'fee', 'feed', 'feedback', 'female',
    'fiction', 'fierce', 'figure', 'file', 'film', 'final', 'finance',
    'finding', 'fine', 'firm', 'fiscal', 'flag', 'flame', 'flash',
    'flat', 'flavour', 'flesh', 'flexible', 'flight', 'float', 'flood',
    'floor', 'flour', 'flow', 'flower', 'fold', 'folk', 'following',
    'fool', 'football', 'force', 'foreign', 'forest', 'forever', 'forgive',
    'formal', 'formation', 'former', 'formula', 'forth', 'fortune',
    'forum', 'forward', 'fossil', 'foster', 'foundation', 'founder',
    'frame', 'framework', 'franchise', 'fraud', 'frequent', 'fresh',
    'friction', 'frontier', 'fruit', 'frustration', 'fuel', 'fulfil',
    'function', 'fund', 'fundamental', 'funeral', 'furniture', 'furthermore',
    'gallery', 'gap', 'garage', 'garlic', 'gather', 'gear', 'gender',
    'gene', 'generate', 'generation', 'generous', 'genius', 'gentle',
    'genuine', 'gesture', 'gift', 'glad', 'glance', 'global', 'glory',
    'goal', 'govern', 'grab', 'grace', 'grade', 'gradually', 'grain',
    'grand', 'grant', 'graphic', 'grass', 'grave', 'greatly', 'green',
    'grey', 'grief', 'grin', 'grip', 'grocery', 'gross', 'guard',
    'guarantee', 'guess', 'guest', 'guide', 'guilty', 'habit', 'hall',
    'halt', 'handful', 'handle', 'handsome', 'hang', 'harm', 'harmony',
    'harvest', 'hatred', 'heal', 'health', 'healthy', 'heap', 'heat',
    'heaven', 'heel', 'height', 'heritage', 'hero', 'hide', 'highlight',
    'highway', 'hill', 'hint', 'hip', 'hire', 'historian', 'historical',
    'hit', 'hold', 'holy', 'honour', 'hook', 'hope', 'horizon',
    'horror', 'host', 'household', 'housing', 'humour', 'hunt',
    'hurry', 'hurt', 'ideal', 'illegal', 'illustrate', 'image',
    'imagination', 'imagine', 'immediate', 'immigrant', 'immune',
    'impact', 'implement', 'implication', 'imply', 'import', 'impose',
    'impress', 'impression', 'impressive', 'improve', 'improvement',
    'incident', 'income', 'incredible', 'independent', 'index',
    'indicate', 'indirect', 'individual', 'industrial', 'industry',
    'inevitable', 'infant', 'infection', 'inflation', 'influence',
    'inform', 'initial', 'initiative', 'injure', 'innocent', 'innovation',
    'input', 'inquiry', 'insist', 'inspect', 'inspire', 'install',
    'instance', 'institution', 'instruction', 'instrument', 'insurance',
    'intellectual', 'intelligence', 'intend', 'intense', 'intention',
    'interact', 'interest', 'interior', 'internal', 'interpret',
    'interval', 'intimate', 'introduction', 'invasion', 'invest',
    'investigate', 'investment', 'investor', 'invitation', 'involve',
    'iron', 'island', 'isolate', 'issue', 'item', 'jacket', 'jail',
    'jewel', 'joint', 'journal', 'journalist', 'journey', 'judge',
    'juice', 'jump', 'junior', 'jury', 'justice', 'justify', 'keen',
    'keyboard', 'kick', 'kit', 'knee', 'knife', 'knock', 'label',
    'labour', 'lack', 'ladder', 'lady', 'lake', 'landscape', 'lane',
    'lap', 'launch', 'laundry', 'lawn', 'lawsuit', 'layer', 'lead',
    'lean', 'leather', 'lecture', 'legislation', 'length', 'lesson',
    'liberal', 'library', 'license', 'lifestyle', 'lifetime', 'lift',
    'limit', 'limitation', 'line', 'link', 'lip', 'liquid', 'list',
    'literature', 'load', 'loan', 'lobby', 'lock', 'logic', 'long-term',
    'loose', 'lover', 'lower', 'luck', 'luggage', 'lung', 'luxury',
    'magazine', 'magnetic', 'magnitude', 'maintain', 'major', 'majority',
    'manage', 'manifest', 'manner', 'manufacture', 'margin', 'marine',
    'marker', 'mass', 'massive', 'master', 'match', 'mate', 'material',
    'mathematics', 'maximum', 'mayor', 'meanwhile', 'measure',
    'mechanism', 'media', 'medium', 'membership', 'memory', 'mental',
    'mention', 'merchant', 'mercy', 'mere', 'merely', 'merge', 'merit',
    'method', 'middle', 'might', 'mild', 'militia', 'million', 'mine',
    'mineral', 'minimum', 'minister', 'minor', 'minority', 'miracle',
    'mirror', 'missile', 'mission', 'mist', 'mixture', 'mobile',
    'moderate', 'modest', 'modify', 'monitor', 'mood', 'moral',
    'moreover', 'mortgage', 'mostly', 'motion', 'motivate', 'mount',
    'mouse', 'multiple', 'murder', 'muscle', 'mutual', 'mystery',
    'myth', 'naked', 'narrative', 'narrow', 'nasty', 'nation',
    'native', 'natural', 'naval', 'neat', 'necessity', 'negative',
    'negotiate', 'nerve', 'neutral', 'nevertheless', 'nightmare',
    'noble', 'nod', 'noise', 'nomination', 'nonetheless', 'nonsense',
    'normal', 'normally', 'notable', 'note', 'notice', 'notion',
    'novel', 'nowadays', 'nuclear', 'nurse', 'nutrition', 'obey',
    'object', 'objective', 'obligation', 'observation', 'observe',
    'obstacle', 'obtain', 'obvious', 'occasion', 'occupation', 'occupy',
    'occur', 'offence', 'offend', 'offensive', 'offering', 'official',
    'oil', 'opening', 'operate', 'operation', 'opponent', 'opportunity',
    'oppose', 'opposite', 'opposition', 'ordinary', 'organic',
    'organisation', 'organize', 'orientation', 'origin', 'original',
    'otherwise', 'outcome', 'outdoor', 'output', 'outstanding', 'overcome',
    'overlook', 'overseas', 'overtake', 'overview', 'owe', 'ownership',
    'pace', 'pack', 'package', 'pad', 'painful', 'paint', 'pair',
    'palace', 'pale', 'panel', 'panic', 'paragraph', 'parallel',
    'parcel', 'parent', 'parking', 'parliament', 'partial', 'participate',
    'particular', 'partly', 'partnership', 'passage', 'passion',
    'passive', 'patent', 'path', 'patience', 'patient', 'patrol',
    'pattern', 'pause', 'payment', 'peace', 'peak', 'peer', 'penalty',
    'pension', 'perceive', 'percentage', 'perception', 'perfect',
    'perform', 'performance', 'permit', 'personality', 'perspective',
    'phase', 'phenomenon', 'philosophy', 'phrase', 'physical',
    'pile', 'pilot', 'pin', 'pitch', 'plain', 'planet', 'plate',
    'platform', 'pleasure', 'plenty', 'plot', 'plug', 'pocket',
    'poem', 'poet', 'poetry', 'poison', 'policy', 'polish', 'poll',
    'pond', 'pool', 'poor', 'pop', 'popular', 'populate', 'population',
    'portion', 'portrait', 'pose', 'position', 'positive', 'possess',
    'possession', 'potential', 'pour', 'poverty', 'powder', 'powerful',
    'practical', 'practice', 'praise', 'pray', 'prayer', 'precise',
    'predict', 'prefer', 'pregnant', 'prejudice', 'preliminary',
    'premise', 'premium', 'preparation', 'prepare', 'presence',
    'present', 'presentation', 'preserve', 'president', 'press',
    'pressure', 'pretend', 'pretty', 'prevail', 'prevent', 'previous',
    'previously', 'pride', 'primarily', 'primary', 'prime', 'prince',
    'princess', 'principal', 'principle', 'print', 'prior', 'priority',
    'prison', 'prisoner', 'privacy', 'private', 'privilege', 'prize',
    'probe', 'proceed', 'process', 'produce', 'producer', 'product',
    'production', 'profession', 'professional', 'profile', 'profit',
    'program', 'programme', 'progress', 'project', 'prominent', 'promote',
    'promotion', 'proof', 'proper', 'properly', 'property', 'proportion',
    'proposal', 'propose', 'prosecution', 'prospect', 'protect',
    'protection', 'protest', 'prove', 'provide', 'provider', 'province',
    'provision', 'psychological', 'psychology', 'publication', 'publish',
    'punishment', 'purchase', 'pure', 'pursue', 'qualify', 'quarter',
    'quote', 'racial', 'radical', 'rage', 'rail', 'raise', 'random',
    'range', 'rank', 'rapid', 'rare', 'rate', 'rather', 'ratio',
    'raw', 'react', 'reaction', 'reality', 'realize', 'reasonable',
    'rebel', 'recall', 'receive', 'recognition', 'recommend',
    'recommendation', 'record', 'recover', 'recovery', 'recruit',
    'reduce', 'reduction', 'refer', 'reference', 'reflect', 'reflection',
    'reform', 'refugee', 'refuse', 'regard', 'regime', 'region',
    'register', 'regulate', 'regulation', 'reject', 'relate',
    'relation', 'relative', 'release', 'relevant', 'relief', 'rely',
    'remain', 'remark', 'remarkable', 'remedy', 'remote', 'removal',
    'render', 'renew', 'repeat', 'replace', 'replacement', 'report',
    'reporter', 'represent', 'representative', 'republic', 'reputation',
    'request', 'require', 'requirement', 'rescue', 'research',
    'researcher', 'reserve', 'resident', 'resign', 'resist',
    'resistance', 'resolution', 'resolve', 'resort', 'resource',
    'respond', 'response', 'restore', 'restrict', 'restriction',
    'retain', 'retire', 'retirement', 'reveal', 'revenue', 'reverse',
    'review', 'revolution', 'rhythm', 'rice', 'ride', 'ridge', 'rifle',
    'ring', 'riot', 'rip', 'risk', 'rival', 'river', 'robot', 'rocket',
    'roof', 'root', 'rope', 'rough', 'routine', 'royal', 'rub', 'ruin',
    'rural', 'rush', 'sacred', 'sacrifice', 'sake', 'salary', 'sample',
    'satellite', 'satisfy', 'sauce', 'scale', 'scandal', 'scenario',
    'scene', 'schedule', 'scheme', 'scholar', 'scope', 'score',
    'scratch', 'screen', 'script', 'sector', 'secure', 'seek', 'segment',
    'seize', 'select', 'senate', 'senator', 'senior', 'sensitive',
    'sequence', 'series', 'serve', 'session', 'settle', 'settlement',
    'severe', 'shadow', 'shake', 'shall', 'shame', 'shape', 'share',
    'sharp', 'shed', 'shell', 'shelter', 'shift', 'shine', 'ship',
    'shirt', 'shock', 'shoot', 'shore', 'shortage', 'shortly', 'shot',
    'shoulder', 'shout', 'shut', 'shuttle', 'sigh', 'sight', 'signal',
    'significance', 'significant', 'silence', 'silk', 'silly', 'silver',
    'similar', 'similarly', 'slight', 'slip', 'slope', 'smart', 'smooth',
    'snap', 'so-called', 'so-called', 'social', 'software', 'soil',
    'solar', 'solid', 'solution', 'solve', 'somewhat', 'sophisticated',
    'soul', 'southern', 'sovereign', 'spare', 'spark', 'species',
    'specific', 'specify', 'spectacular', 'spectrum', 'speculate',
    'spokesman', 'sponsor', 'spread', 'spring', 'spy', 'squad',
    'squeeze', 'stable', 'stadium', 'staff', 'stake', 'stand',
    'standard', 'standing', 'stare', 'starve', 'statistic', 'status',
    'steady', 'steam', 'steel', 'steep', 'stem', 'stereotype', 'stick',
    'stir', 'stock', 'storm', 'straight', 'strain', 'strand', 'stranger',
    'strategic', 'strategy', 'stream', 'strength', 'stress', 'stretch',
    'strict', 'strike', 'string', 'strip', 'stroke', 'strongly',
    'structure', 'struggle', 'stuck', 'stuff', 'substantial', 'substitute',
    'suburb', 'succeed', 'succession', 'successive', 'sue', 'suffer',
    'sufficient', 'sugar', 'suggest', 'suggestion', 'suit', 'suitable',
    'sum', 'superior', 'supplement', 'supply', 'supporter', 'suppose',
    'suppress', 'supreme', 'surface', 'surgery', 'surplus', 'surprise',
    'surprising', 'surprisingly', 'surrender', 'surround', 'survey',
    'survival', 'survive', 'suspect', 'suspend', 'sustain', 'swap',
    'swear', 'sweep', 'sweet', 'swing', 'switch', 'symbol', 'sympathy',
    'symptom', 'tackle', 'tale', 'talent', 'tank', 'tap', 'tape',
    'target', 'technique', 'temperature', 'temporary', 'tenant',
    'tendency', 'tension', 'terminal', 'terms', 'terrain', 'terrible',
    'territory', 'terrorism', 'terrorist', 'testimony', 'testing',
    'text', 'texture', 'theme', 'theory', 'therapy', 'threat',
    'threaten', 'threshold', 'thrive', 'tide', 'tight', 'till', 'tissue',
    'title', 'tobacco', 'tone', 'tonnes', 'torture', 'total', 'tough',
    'tour', 'tourism', 'tournament', 'trace', 'track', 'tradition',
    'traditional', 'traffic', 'tragedy', 'trail', 'trait', 'transaction',
    'transform', 'transition', 'transmit', 'transport', 'trap', 'trauma',
    'travel', 'treasure', 'treat', 'treaty', 'trend', 'trial', 'tribal',
    'tribe', 'trick', 'trigger', 'triumph', 'troop', 'tropical', 'truck',
    'trust', 'tube', 'tunnel', 'twin', 'twist', 'typical', 'ultimate',
    'ultimately', 'uncover', 'undergo', 'underline', 'undermine',
    'unemployment', 'unfair', 'unified', 'union', 'unique', 'unite',
    'unity', 'universal', 'universe', 'unlike', 'unlikely', 'update',
    'upgrade', 'urban', 'urge', 'used', 'useful', 'utility', 'utterly',
    'vacation', 'vague', 'valid', 'valley', 'valuable', 'van', 'variable',
    'variation', 'variety', 'vehicle', 'venture', 'version', 'versus',
    'vertical', 'vessel', 'veteran', 'viable', 'victim', 'video',
    'view', 'violate', 'violation', 'virtual', 'virtually', 'virtue',
    'visible', 'vision', 'visual', 'vital', 'vivid', 'vocabulary',
    'volume', 'voluntary', 'volunteer', 'vulnerable', 'wage', 'wake',
    'wander', 'ward', 'warehouse', 'warn', 'warning', 'warrant',
    'warrior', 'waste', 'wave', 'weak', 'weakness', 'wealth', 'weapon',
    'weave', 'welfare', 'well-known', 'wheat', 'wheel', 'wherever',
    'whisper', 'whistle', 'whoever', 'widespread', 'wildlife', 'willing',
    'wind', 'wire', 'wisdom', 'wise', 'wit', 'withdraw', 'witness',
    'wonder', 'wooden', 'workforce', 'workshop', 'worried', 'worth',
    'wound', 'wrap', 'yard', 'yield', 'zone',
]

OXFORD_B1 = [
    'abstract', 'absorb', 'abuse', 'academic', 'accelerate', 'accent',
    'acceptable', 'access', 'accommodate', 'accompany', 'accomplish',
    'account', 'accountability', 'accurate', 'accuse', 'acknowledge',
    'acquire', 'adequate', 'adjacent', 'adjust', 'administration',
    'administrator', 'admire', 'admission', 'adolescent', 'adopt',
    'advance', 'advanced', 'advantage', 'adventure', 'advert', 'advocate',
    'aesthetic', 'affect', 'affection', 'afford', 'aggressive', 'agony',
    'agriculture', 'aid', 'aircraft', 'aisle', 'alarm', 'alcohol',
    'alert', 'alien', 'align', 'alliance', 'allocate', 'allowance',
    'ally', 'alongside', 'altogether', 'aluminium', 'amateur',
    'amaze', 'ambassador', 'ambiguous', 'ambition', 'ambulance',
    'amend', 'amidst', 'analogy', 'analyse', 'ancestor', 'anchor',
    'angel', 'anniversary', 'annoy', 'anonymous', 'anticipate',
    'anxiety', 'anyhow', 'apparent', 'apparently', 'appeal', 'appetite',
    'applaud', 'applicable', 'applicant', 'application', 'appoint',
    'appreciation', 'apprentice', 'appropriate', 'approve', 'approximate',
    'architect', 'arena', 'arguably', 'arise', 'army', 'arouse',
    'array', 'arrest', 'arrogant', 'articulate', 'aside', 'aspire',
    'assassination', 'assault', 'assemble', 'assembly', 'assert',
    'assess', 'asset', 'assign', 'assist', 'associate', 'assume',
    'assure', 'atlas', 'atmosphere', 'attach', 'attain', 'attempt',
    'attend', 'attribute', 'auction', 'audit', 'autonomy', 'availability',
    'average', 'avoid', 'await', 'awesome', 'awkward', 'backdrop',
    'backwards', 'bacon', 'bail', 'balanced', 'ballet', 'balloon',
    'ballot', 'ban', 'band', 'bankrupt', 'banner', 'bare', 'barely',
    'bargain', 'barrel', 'barrier', 'baseball', 'basement', 'battery',
    'battle', 'bay', 'beam', 'beast', 'behalf', 'benchmark', 'bend',
    'beneficial', 'beside', 'bet', 'bias', 'bid', 'biscuit', 'blade',
    'blanket', 'blast', 'bleed', 'blend', 'bless', 'blind', 'bliss',
    'block', 'blog', 'blonde', 'bloom', 'blow', 'blueprint', 'blunt',
    'boast', 'bold', 'bomb', 'bonfire', 'boost', 'border', 'bore',
    'bounce', 'bound', 'boundary', 'bow', 'brake', 'brand', 'breach',
    'breed', 'brick', 'brief', 'brilliant', 'broad', 'broadcast',
    'broker', 'browse', 'brutal', 'bubble', 'bucket', 'budget',
    'buffet', 'bulk', 'bullet', 'bulletin', 'bump', 'bunch', 'burden',
    'bureau', 'burial', 'burst', 'butterfly', 'cabin', 'cable',
    'calculate', 'campaign', 'cancel', 'candidate', 'candle', 'canvas',
    'capable', 'capacity', 'capitalism', 'capture', 'carbon', 'career',
    'cargo', 'carriage', 'carve', 'casino', 'casual', 'catalogue',
    'catastrophe', 'category', 'cater', 'cattle', 'caution', 'cease',
    'cemetery', 'census', 'ceremony', 'certificate', 'chamber',
    'champion', 'championship', 'chaos', 'chapter', 'characteristic',
    'charity', 'charm', 'charter', 'chase', 'cheat', 'cheer',
    'chemical', 'cherish', 'chew', 'chill', 'chip', 'chorus',
    'chronic', 'chunk', 'circuit', 'circulate', 'circumstance',
    'civilian', 'civilization', 'clarify', 'clarity', 'clash',
    'classic', 'classify', 'clause', 'clerk', 'click', 'client',
    'cliff', 'clinic', 'clip', 'clockwise', 'clone', 'cluster',
    'coalition', 'cocktail', 'cognitive', 'coincide', 'collaborate',
    'collapse', 'colony', 'combat', 'comedy', 'commander', 'commence',
    'commentary', 'commerce', 'commission', 'commodity', 'communist',
    'companion', 'comparable', 'comparison', 'compassion', 'compel',
    'compensate', 'compile', 'complement', 'complex', 'compliance',
    'complicated', 'component', 'compose', 'compound', 'comprehensive',
    'comprise', 'compromise', 'compulsory', 'compute', 'conceal',
    'conceive', 'concentrate', 'concept', 'concern', 'concession',
    'conclude', 'concrete', 'condemn', 'conduct', 'confess',
    'confidence', 'confine', 'confirm', 'conflict', 'confront',
    'confuse', 'congress', 'conscience', 'conscious', 'consensus',
    'consent', 'consequence', 'conservation', 'conservative',
    'considerable', 'considerably', 'consist', 'consistent',
    'constant', 'constitute', 'constitution', 'construct', 'consult',
    'consume', 'consumption', 'contemplate', 'contemporary', 'contempt',
    'contest', 'context', 'continent', 'contract', 'contradict',
    'contrary', 'contrast', 'contribute', 'controversial', 'controversy',
    'convention', 'convert', 'convey', 'convict', 'conviction',
    'convince', 'cooperate', 'coordinate', 'cope', 'copyright',
    'corporate', 'correspond', 'correspondent', 'corridor', 'corrupt',
    'corruption', 'council', 'counter', 'counterpart', 'county',
    'coup', 'courage', 'course', 'court', 'courtesy', 'coverage',
    'crack', 'craft', 'crane', 'crash', 'crawl', 'creation',
    'creative', 'creature', 'credibility', 'credit', 'crew', 'crime',
    'criminal', 'cripple', 'crisis', 'criteria', 'critic', 'critical',
    'criticism', 'criticize', 'crop', 'crude', 'crush', 'crystal',
    'cue', 'cult', 'cultivate', 'cultural', 'currency', 'curriculum',
    'curtain', 'curve', 'custody', 'custom', 'cutting', 'cyber',
    'cycle', 'dam', 'database', 'dawn', 'deadline', 'debate',
    'debut', 'decay', 'deceive', 'decent', 'deck', 'declaration',
    'declare', 'decline', 'decorate', 'decoration', 'decrease',
    'dedicate', 'deem', 'default', 'defeat', 'defend', 'defender',
    'deficit', 'define', 'definite', 'definitely', 'definition',
    'defy', 'delegate', 'deliberate', 'deliberately', 'delicate',
    'delight', 'deliver', 'delivery', 'demand', 'democracy',
    'democratic', 'demonstrate', 'demonstration', 'dense', 'deny',
    'depart', 'department', 'departure', 'depend', 'deposit',
    'depression', 'deprive', 'derive', 'descend', 'describe',
    'description', 'desert', 'deserve', 'design', 'designer',
    'desirable', 'desire', 'desperate', 'desperately', 'despite',
    'destination', 'destiny', 'destroy', 'destruction', 'detail',
    'detect', 'detection', 'determination', 'determine', 'device',
    'devote', 'diagnose', 'diagram', 'dialogue', 'diamond', 'diet',
    'differ', 'digest', 'digital', 'dilemma', 'dimension', 'diminish',
    'dinosaur', 'diplomat', 'disabled', 'disagree', 'disappear',
    'disappoint', 'disaster', 'disc', 'discipline', 'disclose',
    'discount', 'discourse', 'discover', 'discovery', 'discrimination',
    'disguise', 'dismiss', 'disorder', 'display', 'disposal',
    'dispose', 'dispute', 'dissolve', 'distinct', 'distinction',
    'distinguish', 'distribute', 'distribution', 'district', 'disturb',
    'diverse', 'diversity', 'divide', 'division', 'divorce', 'doctrine',
    'document', 'domain', 'domestic', 'dominant', 'dominate', 'donation',
    'donor', 'dose', 'downtown', 'draft', 'drag', 'dragon', 'drain',
    'drama', 'dramatic', 'dramatically', 'drift', 'drill', 'driver',
    'drought', 'drown', 'drunk', 'dull', 'dump', 'duration', 'dusk',
    'dust', 'duty', 'dwell', 'dynamic', 'eager', 'earn', 'earnings',
    'ease', 'echo', 'eclipse', 'ecological', 'economics', 'editorial',
    'educate', 'effective', 'effectively', 'efficient', 'efficiently',
    'elaborate', 'elderly', 'elect', 'election', 'electoral', 'electric',
    'electrical', 'electronic', 'elegant', 'element', 'elevate',
    'eligible', 'eliminate', 'elite', 'embrace', 'emerge', 'emergency',
    'emission', 'emotion', 'emotional', 'emphasis', 'emphasize',
    'empire', 'empirical', 'employment', 'enable', 'encounter',
    'encourage', 'endorse', 'endure', 'enforce', 'engage', 'engagement',
    'engine', 'engineering', 'enhance', 'enormous', 'enquiry', 'enrich',
    'ensure', 'enterprise', 'enthusiasm', 'entire', 'entirely',
    'entitle', 'entity', 'entrepreneur', 'entry', 'envelope',
    'environment', 'episode', 'equality', 'equip', 'equipment',
    'equivalent', 'era', 'erode', 'erosion', 'error', 'escape',
    'especially', 'essay', 'essence', 'essential', 'essentially',
    'establish', 'estate', 'estimate', 'ethical', 'evaluate', 'evaluation',
    'evidence', 'evident', 'evil', 'evolution', 'evolve', 'exaggerate',
    'examination', 'examine', 'exceed', 'exception', 'exceptional',
    'excess', 'exchange', 'excitement', 'exclude', 'exclusion',
    'exclusive', 'exclusively', 'excuse', 'execute', 'execution',
    'exempt', 'exercise', 'exert', 'exhibit', 'exhibition', 'exile',
    'expand', 'expansion', 'expectation', 'expense', 'experimental',
    'expert', 'explicit', 'explicitly', 'exploit', 'exploitation',
    'explore', 'explosion', 'export', 'expose', 'exposure', 'extend',
    'extension', 'extensive', 'extent', 'external', 'extraordinary',
    'extreme', 'extremely', 'fabric', 'facility', 'factor', 'faculty',
    'fade', 'failure', 'faith', 'fame', 'familiar', 'fantasy', 'fare',
    'fascinate', 'fashion', 'fatal', 'fate', 'fault', 'favour',
    'favourite', 'feasibility', 'feature', 'federal', 'feedback',
    'female', 'feminist', 'fiction', 'fierce', 'figure', 'file',
    'film', 'filter', 'final', 'finally', 'finance', 'finding',
    'fine', 'firm', 'fiscal', 'fitness', 'flag', 'flame', 'flash',
    'flat', 'flavour', 'flee', 'flesh', 'flexibility', 'flexible',
    'float', 'flock', 'flood', 'flour', 'flow', 'fluctuate',
    'focus', 'folk', 'following', 'footstep', 'forecast', 'foreign',
    'foresee', 'forest', 'forever', 'forgive', 'formal', 'formation',
    'former', 'formula', 'forth', 'fortune', 'forum', 'forward',
    'fossil', 'foster', 'foundation', 'founder', 'fraction', 'fragment',
    'frame', 'framework', 'franchise', 'frank', 'fraud', 'free',
    'freedom', 'freeze', 'frequency', 'frequent', 'frequently',
    'fresh', 'friction', 'frontier', 'frustrate', 'frustration',
    'fuel', 'fulfil', 'function', 'fund', 'fundamental', 'funeral',
    'furthermore', 'gallery', 'gap', 'garage', 'garbage', 'garden',
    'gather', 'gear', 'gender', 'gene', 'generate', 'generation',
    'generous', 'genius', 'gentle', 'genuine', 'gesture', 'giant',
    'gift', 'glad', 'glance', 'global', 'glory', 'goal', 'govern',
    'grab', 'grace', 'grade', 'gradually', 'grain', 'grand', 'grant',
    'graphic', 'grass', 'grave', 'greatly', 'green', 'grief',
    'grin', 'grip', 'grocery', 'gross', 'guard', 'guarantee',
    'guess', 'guest', 'guide', 'guilty', 'guitar', 'habit', 'hall',
    'halt', 'handful', 'handle', 'handsome', 'hang', 'harm',
    'harmony', 'harsh', 'harvest', 'hatred', 'heal', 'health',
    'healthy', 'heap', 'heat', 'heaven', 'heel', 'height',
    'heritage', 'hero', 'hide', 'highlight', 'highway', 'hill',
    'hint', 'hip', 'hire', 'historian', 'historical', 'hit',
    'hold', 'holy', 'honour', 'hook', 'hope', 'horizon',
    'horror', 'host', 'household', 'housing', 'humour', 'hunt',
    'hurry', 'hurt', 'ideal', 'identical', 'identify', 'identity',
    'ideology', 'ignorance', 'ignore', 'illegal', 'illustrate',
    'image', 'imagination', 'imagine', 'immediate', 'immense',
    'immigrant', 'immune', 'impact', 'implement', 'implication',
    'imply', 'import', 'impose', 'impress', 'impression', 'impressive',
    'improve', 'improvement', 'incident', 'income', 'incredible',
    'incredibly', 'independent', 'index', 'indicate', 'indication',
    'indirect', 'individual', 'industrial', 'industry', 'inevitable',
    'inevitably', 'infant', 'infection', 'inflation', 'influence',
    'inform', 'initial', 'initially', 'initiative', 'injure', 'injury',
    'innocent', 'innovation', 'input', 'inquiry', 'insist', 'inspect',
    'inspiration', 'inspire', 'install', 'instance', 'institution',
    'instruction', 'instrument', 'insurance', 'intellectual',
    'intelligence', 'intend', 'intense', 'intensity', 'intention',
    'interact', 'interaction', 'interest', 'interior', 'intermediate',
    'internal', 'interpret', 'interpretation', 'interval', 'intimate',
    'introduction', 'invade', 'invasion', 'invest', 'investigate',
    'investigation', 'investment', 'investor', 'invitation', 'involve',
    'iron', 'island', 'isolate', 'issue', 'item',
]

OXFORD_B2 = [
    'abolish', 'abstract', 'absurd', 'abundance', 'accommodate',
    'accomplish', 'accumulate', 'accurate', 'accusation', 'accuse',
    'acknowledge', 'acquisition', 'acute', 'adapt', 'adequate',
    'adhere', 'adjacent', 'administer', 'administration', 'admission',
    'adolescent', 'advocate', 'aesthetic', 'affiliate', 'affirm',
    'agenda', 'aggression', 'agony', 'ailment', 'albeit', 'alert',
    'alien', 'align', 'allegation', 'allocate', 'alliance', 'alter',
    'alternate', 'alternative', 'amateur', 'ambiguity', 'ambiguous',
    'amend', 'ample', 'analogy', 'anchor', 'anonymous', 'apparatus',
    'apparent', 'apparently', 'appliance', 'applicable', 'appraisal',
    'appreciate', 'apprehend', 'appropriate', 'approximate', 'arbitrary',
    'archive', 'arise', 'array', 'articulate', 'aspiration', 'aspire',
    'assault', 'assemble', 'assert', 'assertion', 'assess', 'asset',
    'assign', 'assimilate', 'assist', 'assume', 'assumption', 'assure',
    'asylum', 'attain', 'attempt', 'attribute', 'audit', 'authentic',
    'authorise', 'autonomy', 'availability', 'avert', 'avid',
    'backdrop', 'bail', 'bankruptcy', 'barrier', 'batch', 'battalion',
    'beforehand', 'benchmark', 'bestow', 'betray', 'bizarre',
    'blanket', 'blast', 'blaze', 'bleed', 'blend', 'bless',
    'blockade', 'blueprint', 'blunt', 'boast', 'bold', 'bolster',
    'bombard', 'bonfire', 'boost', 'bounce', 'bout', 'breach',
    'breed', 'brief', 'briefly', 'brink', 'brisk', 'broad',
    'broaden', 'browse', 'brutal', 'bureaucracy', 'bypass',
    'calibrate', 'campaign', 'cancel', 'candid', 'capability',
    'capacity', 'capsule', 'caption', 'cardinal', 'catastrophe',
    'cater', 'caution', 'census', 'certify', 'chancellor', 'chaos',
    'characterise', 'charitable', 'charter', 'chronic', 'circulate',
    'circulation', 'cite', 'civic', 'civilian', 'clan', 'clarify',
    'clarity', 'classify', 'clause', 'clearance', 'climate', 'clinch',
    'clinical', 'clone', 'cluster', 'coalition', 'cognitive',
    'coincide', 'collaborate', 'collapse', 'colleague', 'colonial',
    'colony', 'combat', 'commemorate', 'commence', 'commend',
    'commentary', 'commerce', 'commission', 'commodity', 'communal',
    'compact', 'comparable', 'comparison', 'compel', 'compensate',
    'compile', 'complement', 'complex', 'compliance', 'complicated',
    'component', 'compose', 'compound', 'comprehensive', 'comprise',
    'compromise', 'compulsory', 'compute', 'conceal', 'conceive',
    'concentrate', 'concept', 'conception', 'concession', 'conclude',
    'concrete', 'condemn', 'conduct', 'confess', 'confine',
    'confirmation', 'conflict', 'conform', 'confront', 'confusion',
    'congregation', 'congress', 'conjecture', 'conjunction', 'conscience',
    'conscious', 'consensus', 'consent', 'consequence', 'conservation',
    'conservative', 'considerable', 'considerably', 'consist',
    'consistent', 'consolidate', 'constitute', 'constitution',
    'construct', 'consult', 'consultant', 'consume', 'consumption',
    'contemplate', 'contemporary', 'contempt', 'contend', 'content',
    'contest', 'context', 'continent', 'contract', 'contradict',
    'contrary', 'contrast', 'contribute', 'controversial', 'controversy',
    'convention', 'convert', 'convey', 'convict', 'conviction',
    'convince', 'cooperate', 'coordinate', 'core', 'corporate',
    'correspond', 'correspondent', 'corridor', 'corrupt', 'corruption',
    'counsel', 'counter', 'counterpart', 'coup', 'coverage', 'crack',
    'craft', 'crawl', 'credentials', 'crew', 'criminal', 'cripple',
    'criteria', 'critical', 'critique', 'crown', 'crucial', 'cruelty',
    'crush', 'crystal', 'culminate', 'cult', 'cultivate', 'cultural',
    'curiosity', 'currency', 'curriculum', 'custody', 'customs',
    'cynical', 'database', 'deadline', 'debate', 'debut', 'decay',
    'deceive', 'decent', 'decisive', 'declaration', 'declare',
    'decline', 'decree', 'dedicate', 'deem', 'default', 'defect',
    'defend', 'defender', 'deficit', 'define', 'definite', 'defy',
    'delegate', 'deliberate', 'deliberately', 'delicate', 'demonstrate',
    'demonstration', 'dense', 'deny', 'depict', 'deploy', 'deprive',
    'derive', 'descend', 'desert', 'designate', 'desirable', 'desire',
    'desperate', 'desperately', 'destiny', 'detect', 'detection',
    'detention', 'deteriorate', 'determination', 'determine', 'devastate',
    'devise', 'devote', 'diagnose', 'differ', 'digest', 'dilemma',
    'dimension', 'diminish', 'diplomat', 'discard', 'disclose',
    'discourse', 'discretion', 'discrimination', 'disguise', 'dismiss',
    'disorder', 'disperse', 'displace', 'disposal', 'dispose',
    'dispute', 'disrupt', 'dissolve', 'distinct', 'distinction',
    'distinguish', 'distort', 'distribute', 'distribution', 'disturb',
    'diverse', 'diversity', 'division', 'doctrine', 'domain',
    'domestic', 'dominant', 'dominate', 'donation', 'donor', 'doom',
    'dose', 'draft', 'drain', 'drastic', 'drift', 'drought',
    'drown', 'durable', 'duration', 'dynamic', 'eager', 'earnings',
    'ease', 'echo', 'ecological', 'economics', 'editorial', 'educate',
    'effective', 'effectively', 'efficient', 'efficiently', 'elaborate',
    'election', 'electoral', 'elegant', 'element', 'elevate', 'eligible',
    'eliminate', 'elite', 'embrace', 'emerge', 'emergency', 'emission',
    'emotional', 'emphasis', 'emphasize', 'empirical', 'enable',
    'encounter', 'encourage', 'endorse', 'endure', 'enforce', 'engage',
    'engagement', 'enhance', 'enormous', 'enrich', 'ensure', 'enterprise',
    'enthusiasm', 'entitle', 'entity', 'entrepreneur', 'envisage',
    'episode', 'equality', 'equip', 'equivalent', 'erode', 'erosion',
    'error', 'escape', 'essence', 'essential', 'essentially', 'establish',
    'estate', 'ethical', 'evaluate', 'evident', 'evil', 'evoke',
    'evolution', 'evolve', 'exaggerate', 'exceed', 'exception',
    'exceptional', 'excess', 'exchange', 'exclude', 'exclusion',
    'exclusive', 'exclusively', 'execute', 'execution', 'exempt',
    'exert', 'exhibit', 'exhibition', 'exile', 'expand', 'expansion',
    'expedition', 'expertise', 'explicit', 'explicitly', 'exploit',
    'exploitation', 'explore', 'explosion', 'export', 'expose',
    'exposure', 'extend', 'extension', 'extensive', 'extent',
    'external', 'extraordinary', 'extreme', 'fabric', 'facet',
    'facility', 'faculty', 'fade', 'failure', 'fake', 'fame',
    'fantasy', 'fare', 'fascinate', 'fatal', 'fate', 'fault',
    'favour', 'feasibility', 'feature', 'federal', 'feedback',
    'female', 'feminist', 'fierce', 'figure', 'file', 'filter',
    'final', 'finally', 'finance', 'finding', 'firm', 'fiscal',
    'fitness', 'flag', 'flame', 'flash', 'flat', 'flavour',
    'flee', 'flesh', 'flexibility', 'flexible', 'float', 'flock',
    'flood', 'flour', 'flow', 'fluctuate', 'focus', 'folk',
    'following', 'footstep', 'forecast', 'foreign', 'foresee',
    'forest', 'forever', 'forgive', 'formal', 'formation', 'former',
    'formula', 'forth', 'fortune', 'forum', 'forward', 'fossil',
    'foster', 'foundation', 'founder', 'fraction', 'fragment',
    'frame', 'framework', 'franchise', 'frank', 'fraud', 'freedom',
    'freeze', 'frequency', 'frequent', 'frequently', 'fresh',
    'friction', 'frontier', 'frustrate', 'frustration', 'fuel',
    'fulfil', 'function', 'fund', 'fundamental', 'funeral',
    'furthermore', 'gallery', 'gap', 'garage', 'garbage', 'garden',
    'gather', 'gear', 'gender', 'gene', 'generate', 'generation',
    'generous', 'genius', 'gentle', 'genuine', 'gesture', 'giant',
    'gift', 'glad', 'glance', 'global', 'glory', 'goal', 'govern',
    'grab', 'grace', 'grade', 'gradually', 'grain', 'grand',
    'grant', 'graphic', 'grass', 'grave', 'greatly', 'green',
    'grief', 'grin', 'grip', 'grocery', 'gross', 'guard',
    'guarantee', 'guess', 'guest', 'guide', 'guilty', 'guitar',
    'habit', 'hall', 'halt', 'handful', 'handle', 'handsome',
    'hang', 'harm', 'harmony', 'harsh', 'harvest', 'hatred',
    'heal', 'health', 'healthy', 'heap', 'heat', 'heaven',
    'heel', 'height', 'heritage', 'hero', 'hide', 'highlight',
    'highway', 'hill', 'hint', 'hip', 'hire', 'historian',
    'historical', 'hit', 'hold', 'holy', 'honour', 'hook',
    'hope', 'horizon', 'horror', 'host', 'household', 'housing',
    'humour', 'hunt', 'hurry', 'hurt', 'ideal', 'identical',
    'identify', 'identity', 'ideology', 'ignorance', 'ignore',
    'illegal', 'illustrate', 'image', 'imagination', 'imagine',
    'immediate', 'immense', 'immigrant', 'immune', 'impact',
    'implement', 'implication', 'imply', 'import', 'impose',
    'impress', 'impression', 'impressive', 'improve', 'improvement',
    'incident', 'income', 'incredible', 'incredibly', 'independent',
    'index', 'indicate', 'indication', 'indirect', 'individual',
    'industrial', 'industry', 'inevitable', 'inevitably', 'infant',
    'infection', 'inflation', 'influence', 'inform', 'initial',
    'initially', 'initiative', 'injure', 'injury', 'innocent',
    'innovation', 'input', 'inquiry', 'insist', 'inspect',
    'inspiration', 'inspire', 'install', 'instance', 'institution',
    'instruction', 'instrument', 'insurance', 'intellectual',
    'intelligence', 'intend', 'intense', 'intensity', 'intention',
    'interact', 'interaction', 'interest', 'interior', 'intermediate',
    'internal', 'interpret', 'interpretation', 'interval', 'intimate',
    'introduction', 'invade', 'invasion', 'invest', 'investigate',
    'investigation', 'investment', 'investor', 'invitation', 'involve',
    'iron', 'island', 'isolate', 'issue', 'item',
]

# C1-C2 词汇（精选高频词）
C1_WORDS = [
    'abandon', 'abolish', 'absorb', 'abuse', 'accomplish', 'accord',
    'accumulate', 'acquisition', 'adhere', 'adjacent', 'administer',
    'adverse', 'aesthetic', 'aggregate', 'albeit', 'allegation',
    'allocate', 'alliance', 'alter', 'ambiguous', 'analogy', 'anchor',
    'annotate', 'apparatus', 'applicable', 'arbitrary', 'archive',
    'array', 'articulate', 'aspire', 'assert', 'asset', 'asylum',
    'attorney', 'audit', 'autonomy', 'backdrop', 'bail', 'bankruptcy',
    'benchmark', 'bestow', 'bizarre', 'blueprint', 'bolster',
    'bottleneck', 'breach', 'brochure', 'broker', 'browse', 'brutal',
    'bureaucracy', 'calibrate', 'catalyst', 'cater', 'caution',
    'census', 'ceremony', 'charter', 'chronic', 'circulate', 'cite',
    'civic', 'coalition', 'coherent', 'collaborate', 'commemorate',
    'commence', 'commend', 'commentary', 'commodity', 'communal',
    'compact', 'compatible', 'compel', 'compile', 'complement',
    'compliance', 'compulsory', 'compute', 'conceive', 'condemn',
    'confer', 'configuration', 'confiscate', 'conformity', 'congregate',
    'conjecture', 'conscience', 'consecutive', 'consent', 'conserve',
    'consolidate', 'conspiracy', 'constituent', 'constraint', 'consul',
    'contaminate', 'contempt', 'contend',
]

C2_WORDS = [
    'aberration', 'abhor', 'abide', 'abject', 'ablaze', 'abnormal',
    'abode', 'abolition', 'abrupt', 'absolve', 'abstain', 'absurd',
    'abundance', 'acclaim', 'accolade', 'accrue', 'acquaint', 'acquit',
    'acrimony', 'adamant', 'adept', 'adherent', 'adjourn', 'admonish',
    'advent', 'adversary', 'aegis', 'affable', 'affinity', 'afflict',
    'affluent', 'aftermath', 'aggravate', 'aggrieve', 'agile', 'ailment',
    'alacrity', 'alchemy', 'alibi', 'alienate', 'allegiance', 'alleviate',
    'allot', 'allude', 'allure', 'aloof', 'altercation', 'amalgamate',
    'amass', 'ambivalent', 'ameliorate', 'amiable', 'ample', 'amplify',
    'anarchy', 'anecdotal', 'anguish', 'animosity', 'annex', 'annihilate',
    'anomaly', 'antagonize', 'anthology', 'antiquated', 'apathy',
    'apprehend', 'apprise', 'aptitude', 'archaic', 'ardent', 'arduous',
    'aristocracy', 'aroma', 'arrogance', 'ascend', 'ascertain', 'ascribe',
    'aspersion', 'assiduous', 'astute', 'atrocity', 'attest', 'audacious',
    'auspicious', 'austere', 'avarice',
]


# 补充常见词汇（Oxford列表遗漏的高频词）
SUPPLEMENT_A1 = [
    'able', 'ago', 'ahead', 'bit', 'brought', 'certain', 'clear', 'coming',
    'consider', 'continue', 'dark', 'early', 'easy', 'enjoy', 'especially',
    'everything', 'felt', 'finally', 'following', 'glad', 'gone', 'happen',
    'happy', 'heart', 'history', 'horse', 'human', 'hundred', 'ice',
    'indeed', 'instead', 'interested', 'kept', 'kitchen', 'knowledge',
    'language', 'later', 'laugh', 'least', 'less', 'let', 'living',
    'market', 'matter', 'meaning', 'meant', 'meet', 'memory', 'middle',
    'miles', 'million', 'mind', 'moment', 'months', 'morning', 'moved',
    'music', 'nation', 'nature', 'nearly', 'necessary', 'news', 'nice',
    'none', 'north', 'note', 'noticed', 'ocean', 'offer', 'often',
    'order', 'others', 'paper', 'particular', 'past', 'perfect', 'perhaps',
    'period', 'person', 'picture', 'piece', 'plant', 'please', 'poor',
    'position', 'possible', 'power', 'practice', 'president', 'pretty',
    'promise', 'quite', 'rain', 'rather', 'reach', 'reason', 'recently',
    'result', 'return', 'river', 'round', 'running', 'scene', 'season',
    'seems', 'sense', 'serious', 'service', 'several', 'short', 'shown',
    'simple', 'simply', 'sitting', 'slowly', 'sometimes', 'somewhat',
    'spirit', 'standing', 'starts', 'stories', 'strong', 'suddenly',
    'summer', 'supply', 'table', 'talking', 'thinking', 'today', 'told',
    'tonight', 'total', 'town', 'trouble', 'truly', 'truth', 'usually',
    'waiting', 'walking', 'watching', 'weather', 'welcome', 'western',
    'white', 'whole', 'whose', 'wild', 'window', 'winter', 'wonder',
    'working', 'worried', 'writing', 'written', 'younger',
]

SUPPLEMENT_A2 = [
    'absolutely', 'academic', 'accidentally', 'accomplish', 'accurate',
    'achieve', 'actual', 'addition', 'address', 'admire', 'advance',
    'advantage', 'advice', 'afford', 'ahead', 'airport', 'alarm',
    'amazing', 'ancient', 'angle', 'announcement', 'annual', 'anxious',
    'anyway', 'apartment', 'apologize', 'appearance', 'application',
    'appointment', 'appreciation', 'appropriate', 'argument', 'arrange',
    'arrest', 'arrival', 'aside', 'assistant', 'assume', 'atmosphere',
    'attach', 'attempt', 'attend', 'attention', 'attitude', 'attract',
    'audience', 'authority', 'available', 'average', 'awake', 'award',
    'aware', 'awful', 'background', 'balance', 'basically', 'basket',
    'battery', 'battle', 'bean', 'beard', 'beat', 'beauty', 'bedroom',
    'behavior', 'belong', 'benefit', 'beside', 'beyond', 'billion',
    'birth', 'bite', 'blame', 'blank', 'blanket', 'bleed', 'blind',
    'block', 'blow', 'bomb', 'bond', 'border', 'bother', 'bottom',
    'bowl', 'branch', 'brand', 'brave', 'breast', 'breath', 'breathe',
    'brick', 'brief', 'bright', 'brilliant', 'broad', 'broadcast',
    'brush', 'bug', 'bunch', 'burden', 'burn', 'burst', 'bury',
    'cabin', 'cable', 'calculate', 'calm', 'camp', 'campaign', 'campus',
    'cancel', 'cancer', 'capable', 'capacity', 'capture', 'carbon',
    'career', 'cargo', 'carpet', 'carrot', 'castle', 'casual', 'catch',
    'cattle', 'celebrate', 'cell', 'chain', 'chair', 'challenge',
    'champion', 'chapter', 'character', 'charity', 'chart', 'chase',
    'cheap', 'cheek', 'chemical', 'chest', 'chicken', 'chief', 'chip',
    'circle', 'citizen', 'civil', 'classic', 'classroom', 'clay',
    'click', 'client', 'climate', 'climb', 'cling', 'clock', 'cloth',
    'cloud', 'club', 'clue', 'cluster', 'coast', 'coat', 'code',
    'coin', 'collapse', 'colleague', 'column', 'combine', 'comfort',
    'command', 'comment', 'commission', 'commit', 'committee',
    'communicate', 'comparison', 'compete', 'complaint', 'complex',
    'component', 'concentrate', 'concept', 'conclude', 'conclusion',
    'conduct', 'conference', 'confidence', 'conflict', 'confuse',
    'connect', 'conscious', 'consensus', 'consequence', 'conservative',
    'considerable', 'consist', 'constant', 'construct', 'construction',
    'consultant', 'consumer', 'contact', 'contest', 'context',
    'contract', 'contrast', 'contribute', 'controversial', 'convention',
    'conversation', 'convert', 'convince', 'cooperate', 'cope', 'core',
    'corporate', 'correspond', 'cotton', 'council', 'count', 'county',
    'courage', 'crash', 'crazy', 'cream', 'creative', 'crew', 'crisis',
    'critic', 'critical', 'criticism', 'crop', 'crowd', 'crown',
    'crucial', 'crush', 'crystal', 'cultural', 'currency', 'curriculum',
    'curve', 'customer', 'cycle', 'daily', 'damage', 'dare', 'data',
    'database', 'date', 'deadline', 'deaf', 'deal', 'dear', 'debate',
    'debt', 'decent', 'deck', 'declare', 'decline', 'decorate',
    'decrease', 'define', 'definite', 'definition', 'deliberate',
    'delicate', 'delight', 'deliver', 'delivery', 'demand', 'democracy',
    'demonstrate', 'deny', 'department', 'departure', 'depend', 'deposit',
    'depression', 'derive', 'describe', 'description', 'desert',
    'deserve', 'design', 'designer', 'desire', 'desperate', 'despite',
    'destination', 'destroy', 'detail', 'detect', 'determine', 'device',
    'devote', 'diagram', 'dialogue', 'diamond', 'diary', 'diet', 'dig',
    'dimension', 'direct', 'direction', 'dirt', 'disability', 'disagree',
    'disappear', 'disappoint', 'disaster', 'discipline', 'discount',
    'discover', 'discovery', 'discrimination', 'discuss', 'disease',
    'dismiss', 'display', 'dispute', 'distance', 'distinguish',
    'distribute', 'district', 'divide', 'document', 'domestic',
    'dominant', 'dominate', 'double', 'doubt', 'draft', 'drag', 'drama',
    'dramatic', 'draw', 'drawing', 'dream', 'dress', 'drift', 'drink',
    'drive', 'driver', 'drop', 'drown', 'drug', 'drum', 'dry', 'due',
    'dull', 'dump', 'dust', 'duty', 'dynamic', 'eager', 'earn',
    'earth', 'ease', 'eastern', 'economic', 'economics', 'economy',
    'editor', 'educate', 'effective', 'efficient', 'effort', 'elaborate',
    'elderly', 'elect', 'election', 'electric', 'electronic', 'element',
    'eliminate', 'embrace', 'emerge', 'emergency', 'emission', 'emotion',
    'emphasis', 'empire', 'employ', 'employment', 'enable', 'encounter',
    'encourage', 'enemy', 'engage', 'engine', 'engineering', 'enormous',
    'ensure', 'enterprise', 'entire', 'entirely', 'entrance', 'entry',
    'episode', 'equal', 'equipment', 'era', 'error', 'escape',
    'especially', 'essay', 'essential', 'establish', 'estate', 'estimate',
    'evaluate', 'eventually', 'everyday', 'evidence', 'evil', 'evolution',
    'evolve', 'examination', 'examine', 'excellent', 'exception',
    'exchange', 'exciting', 'exclude', 'excuse', 'execute', 'exercise',
    'exhibit', 'exhibition', 'expand', 'expansion', 'expect', 'expense',
    'experiment', 'expert', 'explain', 'explanation', 'explicit',
    'explore', 'explosion', 'export', 'expose', 'exposure', 'extend',
    'extension', 'extensive', 'extent', 'external', 'extra',
    'extraordinary', 'extreme', 'fabric', 'facility', 'factor',
    'faculty', 'failure', 'faith', 'fame', 'familiar', 'fancy',
    'fantasy', 'fashion', 'fate', 'fault', 'favour', 'fear', 'feature',
    'fee', 'feed', 'feedback', 'female', 'fiction', 'fierce', 'figure',
    'file', 'film', 'final', 'finance', 'finding', 'fine', 'firm',
    'fiscal', 'flag', 'flame', 'flash', 'flat', 'flavour', 'flesh',
    'flexible', 'flight', 'float', 'flood', 'floor', 'flour', 'flow',
    'flower', 'fold', 'folk', 'following', 'fool', 'football', 'force',
    'foreign', 'forest', 'forever', 'forgive', 'formal', 'formation',
    'former', 'formula', 'forth', 'fortune', 'forum', 'forward',
    'fossil', 'foster', 'foundation', 'founder', 'frame', 'framework',
    'franchise', 'fraud', 'frequent', 'fresh', 'friction', 'frontier',
    'fruit', 'frustration', 'fuel', 'fulfil', 'function', 'fund',
    'fundamental', 'funeral', 'furniture', 'furthermore', 'gallery',
    'gap', 'garage', 'garlic', 'gather', 'gear', 'gender', 'gene',
    'generate', 'generation', 'generous', 'genius', 'gentle', 'genuine',
    'gesture', 'gift', 'glad', 'glance', 'global', 'glory', 'goal',
    'govern', 'grab', 'grace', 'grade', 'gradually', 'grain', 'grand',
    'grant', 'graphic', 'grass', 'grave', 'greatly', 'green', 'grey',
    'grief', 'grin', 'grip', 'grocery', 'gross', 'guard', 'guarantee',
    'guess', 'guest', 'guide', 'guilty', 'habit', 'hall', 'halt',
    'handful', 'handle', 'handsome', 'hang', 'harm', 'harmony',
    'harvest', 'hatred', 'heal', 'health', 'healthy', 'heap', 'heat',
    'heaven', 'heel', 'height', 'heritage', 'hero', 'hide', 'highlight',
    'highway', 'hill', 'hint', 'hip', 'hire', 'historian', 'historical',
    'hit', 'hold', 'holy', 'honour', 'hook', 'hope', 'horizon',
    'horror', 'host', 'household', 'housing', 'humour', 'hunt',
    'hurry', 'hurt', 'ideal', 'illegal', 'illustrate', 'image',
    'imagination', 'imagine', 'immediate', 'immigrant', 'immune',
    'impact', 'implement', 'implication', 'imply', 'import', 'impose',
    'impress', 'impression', 'impressive', 'improve', 'improvement',
    'incident', 'income', 'incredible', 'independent', 'index',
    'indicate', 'indirect', 'individual', 'industrial', 'industry',
    'inevitable', 'infant', 'infection', 'inflation', 'influence',
    'inform', 'initial', 'initiative', 'injure', 'innocent', 'innovation',
    'input', 'inquiry', 'insist', 'inspect', 'inspire', 'install',
    'instance', 'institution', 'instruction', 'instrument', 'insurance',
    'intellectual', 'intelligence', 'intend', 'intense', 'intention',
    'interact', 'interest', 'interior', 'internal', 'interpret',
    'interval', 'intimate', 'introduction', 'invasion', 'invest',
    'investigate', 'investment', 'investor', 'invitation', 'involve',
    'iron', 'island', 'isolate', 'issue', 'item', 'jacket', 'jail',
    'jewel', 'joint', 'journal', 'journalist', 'journey', 'judge',
    'juice', 'jump', 'junior', 'jury', 'justice', 'justify', 'keen',
    'keyboard', 'kick', 'kit', 'knee', 'knife', 'knock', 'label',
    'labour', 'lack', 'ladder', 'lady', 'lake', 'landscape', 'lane',
    'lap', 'launch', 'laundry', 'lawn', 'lawsuit', 'layer', 'lead',
    'lean', 'leather', 'lecture', 'legislation', 'length', 'lesson',
    'liberal', 'library', 'license', 'lifestyle', 'lifetime', 'lift',
    'limit', 'limitation', 'line', 'link', 'lip', 'liquid', 'list',
    'literature', 'load', 'loan', 'lobby', 'lock', 'logic', 'long-term',
    'loose', 'lover', 'lower', 'luck', 'luggage', 'lung', 'luxury',
    'magazine', 'magnetic', 'magnitude', 'maintain', 'major', 'majority',
    'manage', 'manifest', 'manner', 'manufacture', 'margin', 'marine',
    'marker', 'mass', 'massive', 'master', 'match', 'mate', 'material',
    'mathematics', 'maximum', 'mayor', 'meanwhile', 'measure',
    'mechanism', 'media', 'medium', 'membership', 'memory', 'mental',
    'mention', 'merchant', 'mercy', 'mere', 'merely', 'merge', 'merit',
    'method', 'middle', 'might', 'mild', 'militia', 'million', 'mine',
    'mineral', 'minimum', 'minister', 'minor', 'minority', 'miracle',
    'mirror', 'missile', 'mission', 'mist', 'mixture', 'mobile',
    'moderate', 'modest', 'modify', 'monitor', 'mood', 'moral',
    'moreover', 'mortgage', 'mostly', 'motion', 'motivate', 'mount',
    'mouse', 'multiple', 'murder', 'muscle', 'mutual', 'mystery',
    'myth', 'naked', 'narrative', 'narrow', 'nasty', 'nation',
    'native', 'natural', 'naval', 'neat', 'necessity', 'negative',
    'negotiate', 'nerve', 'neutral', 'nevertheless', 'nightmare',
    'noble', 'nod', 'noise', 'nomination', 'nonetheless', 'nonsense',
    'normal', 'normally', 'notable', 'note', 'notice', 'notion',
    'novel', 'nowadays', 'nuclear', 'nurse', 'nutrition', 'obey',
    'object', 'objective', 'obligation', 'observation', 'observe',
    'obstacle', 'obtain', 'obvious', 'occasion', 'occupation', 'occupy',
    'occur', 'offence', 'offend', 'offensive', 'offering', 'official',
    'oil', 'opening', 'operate', 'operation', 'opponent', 'opportunity',
    'oppose', 'opposite', 'opposition', 'ordinary', 'organic',
    'organisation', 'organize', 'orientation', 'origin', 'original',
    'otherwise', 'outcome', 'outdoor', 'output', 'outstanding',
    'overcome', 'overlook', 'overseas', 'overtake', 'overview', 'owe',
    'ownership', 'pace', 'pack', 'package', 'pad', 'painful', 'paint',
    'pair', 'palace', 'pale', 'panel', 'panic', 'paragraph', 'parallel',
    'parcel', 'parent', 'parking', 'parliament', 'partial', 'participate',
    'particular', 'partly', 'partnership', 'passage', 'passion',
    'passive', 'patent', 'path', 'patience', 'patient', 'patrol',
    'pattern', 'pause', 'payment', 'peace', 'peak', 'peer', 'penalty',
    'pension', 'perceive', 'percentage', 'perception', 'perfect',
    'perform', 'performance', 'permit', 'personality', 'perspective',
    'phase', 'phenomenon', 'philosophy', 'phrase', 'physical',
    'pile', 'pilot', 'pin', 'pitch', 'plain', 'planet', 'plate',
    'platform', 'pleasure', 'plenty', 'plot', 'plug', 'pocket',
    'poem', 'poet', 'poetry', 'poison', 'policy', 'polish', 'poll',
    'pond', 'pool', 'poor', 'pop', 'popular', 'populate', 'population',
    'portion', 'portrait', 'pose', 'position', 'positive', 'possess',
    'possession', 'potential', 'pour', 'poverty', 'powder', 'powerful',
    'practical', 'practice', 'praise', 'pray', 'prayer', 'precise',
    'predict', 'prefer', 'pregnant', 'prejudice', 'preliminary',
    'premise', 'premium', 'preparation', 'prepare', 'presence',
    'present', 'presentation', 'preserve', 'president', 'press',
    'pressure', 'pretend', 'pretty', 'prevail', 'prevent', 'previous',
    'previously', 'pride', 'primarily', 'primary', 'prime', 'prince',
    'princess', 'principal', 'principle', 'print', 'prior', 'priority',
    'prison', 'prisoner', 'privacy', 'private', 'privilege', 'prize',
    'probe', 'proceed', 'process', 'produce', 'producer', 'product',
    'production', 'profession', 'professional', 'profile', 'profit',
    'program', 'programme', 'progress', 'project', 'prominent', 'promote',
    'promotion', 'proof', 'proper', 'properly', 'property', 'proportion',
    'proposal', 'propose', 'prosecution', 'prospect', 'protect',
    'protection', 'protest', 'prove', 'provide', 'provider', 'province',
    'provision', 'psychological', 'psychology', 'publication', 'publish',
    'punishment', 'purchase', 'pure', 'pursue', 'qualify', 'quarter',
    'quote', 'racial', 'radical', 'rage', 'rail', 'raise', 'random',
    'range', 'rank', 'rapid', 'rare', 'rate', 'rather', 'ratio',
    'raw', 'react', 'reaction', 'reality', 'realize', 'reasonable',
    'rebel', 'recall', 'receive', 'recognition', 'recommend',
    'recommendation', 'record', 'recover', 'recovery', 'recruit',
    'reduce', 'reduction', 'refer', 'reference', 'reflect', 'reflection',
    'reform', 'refugee', 'refuse', 'regard', 'regime', 'region',
    'register', 'regulate', 'regulation', 'reject', 'relate',
    'relation', 'relative', 'release', 'relevant', 'relief', 'rely',
    'remain', 'remark', 'remarkable', 'remedy', 'remote', 'removal',
    'render', 'renew', 'repeat', 'replace', 'replacement', 'report',
    'reporter', 'represent', 'representative', 'republic', 'reputation',
    'request', 'require', 'requirement', 'rescue', 'research',
    'researcher', 'reserve', 'resident', 'resign', 'resist',
    'resistance', 'resolution', 'resolve', 'resort', 'resource',
    'respond', 'response', 'restore', 'restrict', 'restriction',
    'retain', 'retire', 'retirement', 'reveal', 'revenue', 'reverse',
    'review', 'revolution', 'rhythm', 'rice', 'ride', 'ridge', 'rifle',
    'ring', 'riot', 'rip', 'risk', 'rival', 'river', 'robot', 'rocket',
    'roof', 'root', 'rope', 'rough', 'routine', 'royal', 'rub', 'ruin',
    'rural', 'rush', 'sacred', 'sacrifice', 'sake', 'salary', 'sample',
    'satellite', 'satisfy', 'sauce', 'scale', 'scandal', 'scenario',
    'scene', 'schedule', 'scheme', 'scholar', 'scope', 'score',
    'scratch', 'screen', 'script', 'sector', 'secure', 'seek', 'segment',
    'seize', 'select', 'senate', 'senator', 'senior', 'sensitive',
    'sequence', 'series', 'serve', 'session', 'settle', 'settlement',
    'severe', 'shadow', 'shake', 'shall', 'shame', 'shape', 'share',
    'sharp', 'shed', 'shell', 'shelter', 'shift', 'shine', 'ship',
    'shirt', 'shock', 'shoot', 'shore', 'shortage', 'shortly', 'shot',
    'shoulder', 'shout', 'shut', 'shuttle', 'sigh', 'sight', 'signal',
    'significance', 'significant', 'silence', 'silk', 'silly', 'silver',
    'similar', 'similarly', 'slight', 'slip', 'slope', 'smart', 'smooth',
    'snap', 'social', 'software', 'soil', 'solar', 'solid', 'solution',
    'solve', 'somewhat', 'sophisticated', 'soul', 'southern', 'sovereign',
    'spare', 'spark', 'species', 'specific', 'specify', 'spectacular',
    'spectrum', 'speculate', 'spokesman', 'sponsor', 'spread', 'spring',
    'spy', 'squad', 'squeeze', 'stable', 'stadium', 'staff', 'stake',
    'stand', 'standard', 'standing', 'stare', 'starve', 'statistic',
    'status', 'steady', 'steam', 'steel', 'steep', 'stem', 'stereotype',
    'stick', 'stir', 'stock', 'storm', 'straight', 'strain', 'strand',
    'stranger', 'strategic', 'strategy', 'stream', 'strength', 'stress',
    'stretch', 'strict', 'strike', 'string', 'strip', 'stroke',
    'strongly', 'structure', 'struggle', 'stuck', 'stuff', 'substantial',
    'substitute', 'suburb', 'succeed', 'succession', 'successive', 'sue',
    'suffer', 'sufficient', 'sugar', 'suggest', 'suggestion', 'suit',
    'suitable', 'sum', 'superior', 'supplement', 'supply', 'supporter',
    'suppose', 'suppress', 'supreme', 'surface', 'surgery', 'surplus',
    'surprise', 'surprising', 'surprisingly', 'surrender', 'surround',
    'survey', 'survival', 'survive', 'suspect', 'suspend', 'sustain',
    'swap', 'swear', 'sweep', 'sweet', 'swing', 'switch', 'symbol',
    'sympathy', 'symptom', 'tackle', 'tale', 'talent', 'tank', 'tap',
    'tape', 'target', 'technique', 'temperature', 'temporary', 'tenant',
    'tendency', 'tension', 'terminal', 'terms', 'terrain', 'terrible',
    'territory', 'terrorism', 'terrorist', 'testimony', 'testing',
    'text', 'texture', 'theme', 'theory', 'therapy', 'threat',
    'threaten', 'threshold', 'thrive', 'tide', 'tight', 'till', 'tissue',
    'title', 'tobacco', 'tone', 'tonnes', 'torture', 'total', 'tough',
    'tour', 'tourism', 'tournament', 'trace', 'track', 'tradition',
    'traditional', 'traffic', 'tragedy', 'trail', 'trait', 'transaction',
    'transform', 'transition', 'transmit', 'transport', 'trap', 'trauma',
    'travel', 'treasure', 'treat', 'treaty', 'trend', 'trial', 'tribal',
    'tribe', 'trick', 'trigger', 'triumph', 'troop', 'tropical', 'truck',
    'trust', 'tube', 'tunnel', 'twin', 'twist', 'typical', 'ultimate',
    'ultimately', 'uncover', 'undergo', 'underline', 'undermine',
    'unemployment', 'unfair', 'unified', 'union', 'unique', 'unite',
    'unity', 'universal', 'universe', 'unlike', 'unlikely', 'update',
    'upgrade', 'urban', 'urge', 'used', 'useful', 'utility', 'utterly',
    'vacation', 'vague', 'valid', 'valley', 'valuable', 'van', 'variable',
    'variation', 'variety', 'vehicle', 'venture', 'version', 'versus',
    'vertical', 'vessel', 'veteran', 'viable', 'victim', 'video',
    'view', 'violate', 'violation', 'virtual', 'virtually', 'virtue',
    'visible', 'vision', 'visual', 'vital', 'vivid', 'vocabulary',
    'volume', 'voluntary', 'volunteer', 'vulnerable', 'wage', 'wake',
    'wander', 'ward', 'warehouse', 'warn', 'warning', 'warrant',
    'warrior', 'waste', 'wave', 'weak', 'weakness', 'wealth', 'weapon',
    'weave', 'welfare', 'wheat', 'wheel', 'wherever', 'whisper',
    'whistle', 'whoever', 'widespread', 'wildlife', 'willing', 'wind',
    'wire', 'wisdom', 'wise', 'wit', 'withdraw', 'witness', 'wonder',
    'wooden', 'workforce', 'workshop', 'worried', 'worth', 'wound',
    'wrap', 'yard', 'yield', 'zone',
]

# 补充常见词（原词表遗漏的高频词根）
SUPPLEMENT_EXTRA = {
    # A1-A2 补充
    'learn': 'A1', 'teach': 'A1', 'school': 'A1', 'class': 'A1',
    'friend': 'A1', 'family': 'A1', 'home': 'A1', 'house': 'A1',
    'city': 'A1', 'country': 'A1', 'world': 'A1', 'street': 'A2',
    'road': 'A1', 'shop': 'A1', 'store': 'A2', 'market': 'A2',
    'office': 'A2', 'hospital': 'A2', 'hotel': 'A2', 'restaurant': 'A2',
    'library': 'A2', 'museum': 'A2', 'church': 'A2', 'park': 'A2',
    'garden': 'A2', 'kitchen': 'A1', 'bathroom': 'A2', 'bedroom': 'A1',
    'door': 'A1', 'window': 'A1', 'floor': 'A1', 'wall': 'A1',
    'table': 'A1', 'chair': 'A1', 'bed': 'A1', 'desk': 'A2',
    'phone': 'A2', 'computer': 'A1', 'internet': 'A2', 'email': 'A2',
    'website': 'A2', 'page': 'A1', 'book': 'A1', 'newspaper': 'A2',
    'magazine': 'A2', 'letter': 'A1', 'story': 'A1', 'article': 'A2',
    'report': 'A2', 'test': 'A1', 'exam': 'A2', 'homework': 'A1',
    'lesson': 'A1', 'class': 'A1', 'student': 'A1', 'teacher': 'A1',
    'professor': 'A2', 'doctor': 'A1', 'nurse': 'A2', 'engineer': 'A2',
    'lawyer': 'A2', 'police': 'A1', 'soldier': 'A2', 'driver': 'A2',
    'worker': 'A1', 'farmer': 'A2', 'cook': 'A1', 'waiter': 'A2',
    'artist': 'A2', 'musician': 'A2', 'actor': 'A2', 'player': 'A1',
    'team': 'A1', 'game': 'A1', 'sport': 'A1', 'ball': 'A1',
    'race': 'A2', 'match': 'A2', 'win': 'A1', 'lose': 'A1',
    'score': 'A2', 'goal': 'A2', 'point': 'A1', 'play': 'A1',
    'run': 'A1', 'walk': 'A1', 'sit': 'A1', 'stand': 'A1',
    'eat': 'A1', 'drink': 'A1', 'sleep': 'A1', 'wake': 'A2',
    'wash': 'A1', 'clean': 'A1', 'cook': 'A1', 'drive': 'A1',
    'fly': 'A1', 'swim': 'A1', 'dance': 'A1', 'sing': 'A1',
    'read': 'A1', 'write': 'A1', 'listen': 'A1', 'watch': 'A1',
    'look': 'A1', 'see': 'A1', 'hear': 'A1', 'feel': 'A1',
    'touch': 'A1', 'smell': 'A1', 'taste': 'A1', 'think': 'A1',
    'know': 'A1', 'understand': 'A1', 'remember': 'A1', 'forget': 'A1',
    'learn': 'A1', 'study': 'A1', 'practice': 'A2', 'try': 'A1',
    'help': 'A1', 'need': 'A1', 'want': 'A1', 'like': 'A1',
    'love': 'A1', 'hate': 'A2', 'hope': 'A1', 'wish': 'A1',
    'believe': 'A1', 'trust': 'A2', 'agree': 'A1', 'disagree': 'A2',
    'decide': 'A1', 'choose': 'A1', 'plan': 'A1', 'prepare': 'A2',
    'begin': 'A1', 'start': 'A1', 'finish': 'A1', 'stop': 'A1',
    'continue': 'A1', 'change': 'A1', 'move': 'A1', 'stay': 'A1',
    'live': 'A1', 'work': 'A1', 'travel': 'A1', 'visit': 'A1',
    'meet': 'A1', 'talk': 'A1', 'speak': 'A1', 'say': 'A1',
    'tell': 'A1', 'ask': 'A1', 'answer': 'A1', 'call': 'A1',
    'open': 'A1', 'close': 'A1', 'turn': 'A1', 'push': 'A1',
    'pull': 'A1', 'carry': 'A1', 'bring': 'A1', 'take': 'A1',
    'give': 'A1', 'get': 'A1', 'put': 'A1', 'make': 'A1',
    'find': 'A1', 'have': 'A1', 'be': 'A1', 'do': 'A1',
    'go': 'A1', 'come': 'A1', 'see': 'A1', 'say': 'A1',
    'get': 'A1', 'make': 'A1', 'know': 'A1', 'think': 'A1',
    'take': 'A1', 'want': 'A1', 'give': 'A1', 'look': 'A1',
    'use': 'A1', 'find': 'A1', 'tell': 'A1', 'ask': 'A1',
    'work': 'A1', 'seem': 'A1', 'feel': 'A1', 'try': 'A1',
    'leave': 'A1', 'call': 'A1', 'keep': 'A1', 'let': 'A1',
    'begin': 'A1', 'show': 'A1', 'hear': 'A1', 'play': 'A1',
    'run': 'A1', 'move': 'A1', 'like': 'A1', 'live': 'A1',
    'believe': 'A1', 'hold': 'A1', 'bring': 'A1', 'happen': 'A1',
    'write': 'A1', 'provide': 'A1', 'sit': 'A1', 'stand': 'A1',
    'lose': 'A1', 'pay': 'A1', 'meet': 'A1', 'include': 'A1',
    'continue': 'A1', 'set': 'A1', 'learn': 'A1', 'change': 'A1',
    'lead': 'A1', 'understand': 'A1', 'watch': 'A1', 'follow': 'A1',
    'stop': 'A1', 'create': 'A1', 'speak': 'A1', 'read': 'A1',
    'allow': 'A1', 'add': 'A1', 'spend': 'A1', 'grow': 'A1',
    'open': 'A1', 'walk': 'A1', 'win': 'A1', 'offer': 'A1',
    'remember': 'A1', 'love': 'A1', 'consider': 'A1', 'appear': 'A1',
    'buy': 'A1', 'wait': 'A1', 'serve': 'A1', 'die': 'A1',
    'send': 'A1', 'expect': 'A1', 'build': 'A1', 'stay': 'A1',
    'fall': 'A1', 'cut': 'A1', 'reach': 'A1', 'kill': 'A1',
    'remain': 'A1', 'suggest': 'A1', 'raise': 'A1', 'pass': 'A1',
    'sell': 'A1', 'require': 'A1', 'report': 'A1', 'decide': 'A1',
    'pull': 'A1', 'develop': 'A1', 'eat': 'A1', 'drink': 'A1',
    # 补充高频词
    'decade': 'B1', 'grammar': 'B1', 'translate': 'B1', 'memorize': 'B1',
    'competence': 'B1', 'learner': 'A2', 'integrate': 'B2',
    'approach': 'A2', 'communicate': 'A2', 'material': 'A2',
    'opportunity': 'A2', 'personal': 'A1', 'experience': 'A1',
    'challenge': 'A2', 'assess': 'B2', 'provide': 'A2', 'meaning': 'A1',
    'significant': 'A2', 'evolve': 'B2', 'expose': 'B2',
    'method': 'A2', 'language': 'A1', 'text': 'A2', 'research': 'A2',
    'focus': 'B2', 'rote': 'B2', 'emphasis': 'B2', 'benefit': 'A2',
    'exposure': 'B2', 'authentic': 'B2', 'progress': 'A2',
    'feedback': 'A2', 'vocabulary': 'A2', 'reading': 'A2',
    'writing': 'A2', 'speaking': 'A2', 'listening': 'A2',
    'pronunciation': 'A2', 'fluency': 'B1', 'accuracy': 'B1',
    'error': 'A2', 'mistake': 'A1', 'correct': 'A1',
    'practice': 'A2', 'exercise': 'A2', 'activity': 'A2',
    'task': 'A2', 'assignment': 'A2', 'project': 'A2',
    'discussion': 'A2', 'presentation': 'A2', 'group': 'A1',
    'pair': 'A2', 'individual': 'A2', 'whole': 'A1',
    'grade': 'A2', 'score': 'A2', 'mark': 'A1', 'result': 'A2',
    'success': 'A2', 'failure': 'A2', 'improve': 'A2', 'develop': 'A2',
    'achieve': 'A2', 'goal': 'A2', 'aim': 'A2', 'objective': 'A2',
    'skill': 'A2', 'ability': 'A2', 'knowledge': 'A1', 'understanding': 'A1',
    'concept': 'A2', 'idea': 'A1', 'theory': 'A2', 'principle': 'A2',
    'rule': 'A1', 'example': 'A1', 'fact': 'A1', 'reason': 'A1',
    'cause': 'A2', 'effect': 'A2', 'result': 'A2', 'consequence': 'A2',
    'problem': 'A1', 'solution': 'A2', 'answer': 'A1', 'question': 'A1',
    'topic': 'A2', 'subject': 'A1', 'theme': 'A2', 'issue': 'A2',
    'area': 'A1', 'field': 'A2', 'domain': 'B2', 'scope': 'B2',
    'aspect': 'A2', 'factor': 'A2', 'element': 'A2', 'feature': 'A2',
    'detail': 'A1', 'example': 'A1', 'instance': 'A2', 'case': 'A1',
    'situation': 'A2', 'condition': 'A2', 'context': 'A2', 'environment': 'A2',
    'process': 'A2', 'system': 'A2', 'structure': 'A2', 'model': 'A2',
    'type': 'A1', 'kind': 'A1', 'form': 'A1', 'part': 'A1',
    'section': 'A2', 'chapter': 'A2', 'paragraph': 'A2', 'sentence': 'A2',
    'word': 'A1', 'phrase': 'A2', 'term': 'A2', 'expression': 'A2',
    'definition': 'A2', 'description': 'A2', 'explanation': 'A2',
    'instruction': 'A2', 'direction': 'A1', 'information': 'A1',
    'knowledge': 'A1', 'data': 'A2', 'evidence': 'A2', 'source': 'A2',
    'reference': 'A2', 'resource': 'A2', 'material': 'A2', 'content': 'A2',
    'message': 'A1', 'communication': 'A2', 'discussion': 'A2',
    'conversation': 'A1', 'dialogue': 'A2', 'interview': 'A2',
    'debate': 'A2', 'argument': 'A2', 'opinion': 'A1', 'view': 'A2',
    'perspective': 'A2', 'position': 'A2', 'attitude': 'A2',
    'approach': 'A2', 'strategy': 'A2', 'method': 'A2', 'technique': 'A2',
    'tool': 'A1', 'resource': 'A2', 'support': 'A2', 'help': 'A1',
    'guide': 'A2', 'instruction': 'A2', 'direction': 'A1',
    'advice': 'A2', 'recommendation': 'A2', 'suggestion': 'A2',
    'proposal': 'A2', 'plan': 'A1', 'program': 'A2', 'project': 'A2',
    'activity': 'A2', 'exercise': 'A2', 'practice': 'A2', 'task': 'A2',
    'assignment': 'A2', 'work': 'A1', 'job': 'A1', 'role': 'A2',
    'function': 'A2', 'purpose': 'A2', 'goal': 'A2', 'aim': 'A2',
    'objective': 'A2', 'target': 'A2', 'standard': 'A2', 'level': 'A1',
    'degree': 'A2', 'extent': 'A2', 'range': 'A2', 'scope': 'B2',
    'scale': 'A2', 'size': 'A1', 'amount': 'A1', 'number': 'A1',
    'quantity': 'A2', 'quality': 'A2', 'value': 'A2', 'worth': 'A2',
    'price': 'A1', 'cost': 'A2', 'expense': 'A2', 'budget': 'A2',
    'income': 'A2', 'revenue': 'B2', 'profit': 'A2', 'loss': 'A2',
    'gain': 'A2', 'benefit': 'A2', 'advantage': 'A2', 'disadvantage': 'A2',
    'strength': 'A2', 'weakness': 'A2', 'opportunity': 'A2', 'threat': 'A2',
    'risk': 'A2', 'danger': 'A1', 'safety': 'A2', 'security': 'A2',
    'protection': 'A2', 'support': 'A2', 'encouragement': 'A2',
    'motivation': 'A2', 'inspiration': 'A2', 'confidence': 'A2',
    'trust': 'A2', 'respect': 'A2', 'responsibility': 'A2',
    'authority': 'A2', 'power': 'A1', 'control': 'A1', 'management': 'A2',
    'leadership': 'A2', 'decision': 'A1', 'choice': 'A1', 'option': 'A2',
    'alternative': 'A2', 'opportunity': 'A2', 'possibility': 'A2',
    'chance': 'A1', 'probability': 'A2', 'likelihood': 'A2',
}


def generate():
    """生成CEFR词表JSON"""
    entries = []
    level_order = {"A1": 1, "A2": 2, "B1": 3, "B2": 4, "C1": 5, "C2": 6}
    word_map = {}

    # 按等级从低到高加载，高等级覆盖低等级
    for word in OXFORD_A1:
        w = word.lower().strip()
        if w: word_map[w] = "A1"
    for word in SUPPLEMENT_A1:
        w = word.lower().strip()
        if w and w not in word_map: word_map[w] = "A1"
    for word in OXFORD_A2:
        w = word.lower().strip()
        if w: word_map[w] = "A2"
    for word in SUPPLEMENT_A2:
        w = word.lower().strip()
        if w and w not in word_map: word_map[w] = "A2"
    for word in OXFORD_B1:
        w = word.lower().strip()
        if w: word_map[w] = "B1"
    for word in OXFORD_B2:
        w = word.lower().strip()
        if w: word_map[w] = "B2"
    for word in C1_WORDS:
        w = word.lower().strip()
        if w: word_map[w] = "C1"
    for word in C2_WORDS:
        w = word.lower().strip()
        if w: word_map[w] = "C2"
    # 补充词（不覆盖已存在的）
    for w, level in SUPPLEMENT_EXTRA.items():
        w = w.lower().strip()
        if w and w not in word_map:
            word_map[w] = level

    # 统计
    counts = {}
    for level in word_map.values():
        counts[level] = counts.get(level, 0) + 1

    print(f"词表统计: {counts}")
    print(f"总计: {len(word_map)} 词")

    # 输出JSON
    for word, level in sorted(word_map.items()):
        entries.append({"word": word, "level": level})

    output_path = os.path.join(os.path.dirname(__file__), "..", "data", "cefr_wordlist.json")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)

    print(f"已保存到: {output_path}")


if __name__ == "__main__":
    generate()
