/**
 * V2-lite Visual Object Engine 的 iframe 内代理脚本。
 * 随 srcdoc 注入课件 HTML（sandbox 无 allow-same-origin，Host 只能靠 postMessage）。
 * 非破坏：底稿不动，CSS/DOM 补丁可整体重放；冻结/悬停框为运行时注入元素，导出时剥离。
 */
export function buildPickAgentScript(channel: string): string {
  const ch = JSON.stringify(channel);
  return [
    "(function(){",
    "if(window.__veAgent)return;window.__veAgent=true;",
    `var CH=${ch};`,
    "function send(t,p){try{parent.postMessage({ve:1,ch:CH,type:t,payload:p||{}},'*')}catch(e){}}",
    "var pickOn=false,curSel=null,hoverBox=null,freezeEl=null;",
    "var patchesDom=[],lastCss='',applying=false;",
    "var editing=false,editEl=null,editOrig=null;",
    "var mo=null,moTimer=0;",
    "function ensureHover(){",
    "if(hoverBox)return;",
    "hoverBox=document.createElement('div');",
    "hoverBox.id='ve-hover-box';",
    "hoverBox.setAttribute('data-ve-ui','hover');",
    "hoverBox.style.cssText='position:fixed;pointer-events:none;z-index:2147483646;border:1.5px dashed #2563eb;background:rgba(37,99,235,.06);display:none';",
    "document.documentElement.appendChild(hoverBox);",
    "}",
    "function setFreeze(on){",
    "if(on&&!freezeEl){freezeEl=document.createElement('style');freezeEl.id='ve-freeze';",
    "freezeEl.textContent='*,*::before,*::after{animation-play-state:paused !important;transition:none !important}';",
    "(document.head||document.documentElement).appendChild(freezeEl);}",
    "if(!on&&freezeEl){freezeEl.parentNode.removeChild(freezeEl);freezeEl=null;}",
    "}",
    "function cssPath(el){",
    "if(!el||el.nodeType!==1)return '';",
    "if(el===document.documentElement)return 'html';",
    "if(el===document.body)return 'body';",
    "var parts=[],e=el,depth=0;",
    "while(e&&e.nodeType===1&&depth<9){",
    "var s=e.tagName.toLowerCase();",
    "var n=1,p=e.previousElementSibling;",
    "while(p){if(p.tagName===e.tagName)n++;p=p.previousElementSibling;}",
    "var hasSame=false,q=e.nextElementSibling;",
    "while(q){if(q.tagName===e.tagName){hasSame=true;break;}q=q.nextElementSibling;}",
    "if(n>1||hasSame)s+=':nth-of-type('+n+')';",
    "parts.unshift(s);",
    "if(e===document.body)break;",
    "e=e.parentElement;depth++;",
    "}",
    "return parts.join(' > ');",
    "}",
    "function info(el){",
    "var r=el.getBoundingClientRect(),cs=getComputedStyle(el);",
    "var chain=[],e=el;",
    "while(e&&e.nodeType===1&&chain.length<9){",
    "chain.unshift({tag:e.tagName.toLowerCase(),component:(e.getAttribute&&e.getAttribute('data-component'))||'',selector:cssPath(e)});",
    "e=e.parentElement;}",
    "return {",
    "tag:el.tagName.toLowerCase(),",
    "id:el.id||'',",
    "cls:(el.getAttribute('class')||'').slice(0,140),",
    "component:el.getAttribute('data-component')||'',",
    "page:el.getAttribute('data-page')||'',",
    "pageTitle:el.getAttribute('data-title')||'',",
    "selector:cssPath(el),",
    "src:el.tagName==='IMG'?(el.getAttribute('src')||'').slice(0,300):'',",
    "rect:{x:r.left,y:r.top,w:r.width,h:r.height},",
    "text:(el.innerText||'').replace(/\\s+/g,' ').slice(0,120),",
    "childCount:el.childElementCount,",
    "styles:{display:cs.display,fontSize:cs.fontSize,fontWeight:cs.fontWeight,fontFamily:String(cs.fontFamily).slice(0,60),color:cs.color,background:cs.backgroundColor,textAlign:cs.textAlign,lineHeight:cs.lineHeight,margin:cs.margin,padding:cs.padding},",
    "chain:chain",
    "};",
    "}",
    "function select(el){curSel=el;send('ve:pick',info(el));}",
    "function sendRect(){",
    "if(curSel&&curSel.parentNode){var r=curSel.getBoundingClientRect();send('ve:rect',{rect:{x:r.left,y:r.top,w:r.width,h:r.height}});}",
    "}",
    "function applyAll(css,dom){",
    "lastCss=css||'';patchesDom=dom||[];",
    "applying=true;",
    "try{",
    "var staleInserts=document.querySelectorAll('[data-ve-insert]');",
    "for(var si=0;si<staleInserts.length;si++){if(staleInserts[si].parentNode)staleInserts[si].parentNode.removeChild(staleInserts[si]);}",
    "var st=document.getElementById('ve-live-patches');",
    "if(!st){st=document.createElement('style');st.id='ve-live-patches';st.setAttribute('data-ve-ui','patches');(document.head||document.documentElement).appendChild(st);}",
    "st.textContent=lastCss;",
    "for(var i=0;i<patchesDom.length;i++){",
    "var p=patchesDom[i],el=null;",
    "try{el=document.querySelector(p.selector)}catch(e){}",
    "if(!el)continue;",
    "if(editing&&el===editEl)continue;",
    "if(p.kind==='text'){if(el.childElementCount===0&&typeof p.newText==='string')el.textContent=p.newText;}",
    "else if(p.kind==='image'){if(el.tagName==='IMG'&&p.newSrc)el.setAttribute('src',p.newSrc);}",
    "else if(p.kind==='insert'&&p.html&&p.position){",
    "var wrap=document.createElement('div');",
    "wrap.setAttribute('data-ve-insert',p.id);",
    "wrap.innerHTML=p.html;",
    "if(p.position==='append')el.appendChild(wrap);",
    "else if(p.position==='before'){if(el.parentNode)el.parentNode.insertBefore(wrap,el);}",
    "else{if(el.parentNode)el.parentNode.insertBefore(wrap,el.nextSibling);}",
    "}",
    "}",
    "}catch(e){}",
    "setTimeout(function(){applying=false;},60);",
    "sendRect();",
    "startObserver();",
    "}",
    "function startObserver(){",
    "if(mo||!window.MutationObserver)return;",
    "mo=new MutationObserver(function(muts){",
    "if(applying||editing||patchesDom.length===0&&lastCss==='')return;",
    "var relevant=false;",
    "for(var i=0;i<muts.length;i++){",
    "var m=muts[i];",
    "if(m.type==='childList'||m.type==='characterData'){relevant=true;break;}",
    "if(m.type==='attributes'&&(m.attributeName==='style'||m.attributeName==='src'||m.attributeName==='class')){relevant=true;break;}",
    "}",
    "if(!relevant)return;",
    "clearTimeout(moTimer);",
    "moTimer=setTimeout(function(){if(!applying&&!editing)applyAll(lastCss,patchesDom);},300);",
    "});",
    "mo.observe(document.documentElement,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['style','src','class']});",
    "}",
    "function startTextEdit(el){",
    "if(editing)return;",
    "editing=true;editEl=el;editOrig=el.textContent;",
    "el.setAttribute('contenteditable','true');",
    "try{el.focus();",
    "var rng=document.createRange();rng.selectNodeContents(el);",
    "var sel=window.getSelection();sel.removeAllRanges();sel.addRange(rng);",
    "}catch(e){}",
    "send('ve:text:started',{selector:cssPath(el)});",
    "}",
    "function endTextEdit(commit){",
    "if(!editing||!editEl)return;",
    "var el=editEl,txt=el.textContent,orig=editOrig;",
    "el.removeAttribute('contenteditable');",
    "try{el.blur();}catch(e){}",
    "editing=false;editEl=null;editOrig=null;",
    "if(commit){send('ve:text:commit',{selector:cssPath(el),text:txt});}",
    "else{el.textContent=orig;}",
    "}",
    "function exportHtml(css){",
    "if(editing)endTextEdit(true);",
    "var clone=document.documentElement.cloneNode(true);",
    "var ce=clone.querySelectorAll('[contenteditable]');",
    "for(var i=0;i<ce.length;i++)ce[i].removeAttribute('contenteditable');",
    "var junk=clone.querySelectorAll('#ve-hover-box,#ve-freeze,[data-ve-agent]');",
    "for(var j=0;j<junk.length;j++){if(junk[j].parentNode)junk[j].parentNode.removeChild(junk[j]);}",
    "var live=clone.querySelector('#ve-live-patches');",
    "if(live){",
    "if(css){live.id='ve-export-patches';live.removeAttribute('data-ve-ui');live.textContent=css;}",
    "else if(live.parentNode){live.parentNode.removeChild(live);}",
    "}",
    "send('ve:export:result',{html:'<!DOCTYPE html>\\n'+clone.outerHTML});",
    "}",
    "document.addEventListener('click',function(ev){",
    "if(!pickOn||editing)return;",
    "ev.preventDefault();ev.stopPropagation();",
    "var el=ev.target;",
    "if(!el||el.nodeType!==1||el===hoverBox)return;",
    "select(el);",
    "},true);",
    "document.addEventListener('dblclick',function(ev){",
    "if(!pickOn||editing)return;",
    "var el=ev.target;",
    "if(!el||el.nodeType!==1||el===hoverBox)return;",
    "if(el.childElementCount>0)return;",
    "ev.preventDefault();ev.stopPropagation();",
    "startTextEdit(el);",
    "},true);",
    "document.addEventListener('mouseover',function(ev){",
    "if(!pickOn||editing)return;",
    "var el=ev.target;",
    "if(!el||el.nodeType!==1||el===hoverBox)return;",
    "ensureHover();",
    "var r=el.getBoundingClientRect();",
    "hoverBox.style.display='block';",
    "hoverBox.style.left=r.left+'px';hoverBox.style.top=r.top+'px';",
    "hoverBox.style.width=r.width+'px';hoverBox.style.height=r.height+'px';",
    "},true);",
    "document.addEventListener('mouseout',function(ev){",
    "if(hoverBox&&ev.target!==hoverBox)hoverBox.style.display='none';",
    "},true);",
    "document.addEventListener('keydown',function(ev){",
    "if(!editing)return;",
    "if(ev.key==='Escape'){ev.preventDefault();endTextEdit(false);}",
    "else if(ev.key==='Enter'&&!ev.shiftKey){ev.preventDefault();endTextEdit(true);}",
    "},true);",
    "document.addEventListener('focusout',function(){",
    "if(editing)setTimeout(function(){if(editing)endTextEdit(true);},0);",
    "},true);",
    "var scrollTimer=0;",
    "function onScrollResize(){",
    "if(!curSel)return;",
    "clearTimeout(scrollTimer);",
    "scrollTimer=setTimeout(sendRect,80);",
    "}",
    "window.addEventListener('scroll',onScrollResize,true);",
    "window.addEventListener('resize',onScrollResize);",
    "window.addEventListener('message',function(ev){",
    "var d=ev.data;",
    "if(!d||d.ve!==1||d.ch!==CH)return;",
    "if(d.type==='ve:pick:set'){",
    "if(editing)endTextEdit(true);",
    "pickOn=!!(d.payload&&d.payload.enabled);",
    "setFreeze(pickOn);",
    "if(!pickOn&&hoverBox)hoverBox.style.display='none';",
    "send('ve:pick:mode',{enabled:pickOn});",
    "}",
    "if(d.type==='ve:pick:goto'){",
    "if(editing)endTextEdit(true);",
    "var el=null;",
    "try{el=document.querySelector((d.payload&&d.payload.selector)||'')}catch(e){}",
    "if(el)select(el);",
    "}",
    "if(d.type==='ve:patches:applyAll'){",
    "applyAll((d.payload&&d.payload.css)||'',(d.payload&&d.payload.patches)||[]);",
    "}",
    "if(d.type==='ve:patches:apply'){",
    "applyAll((d.payload&&d.payload.css)||'',patchesDom);",
    "}",
    "if(d.type==='ve:text:edit'){",
    "var te=null;",
    "try{te=document.querySelector((d.payload&&d.payload.selector)||'')}catch(e){}",
    "if(te&&te.childElementCount===0)startTextEdit(te);",
    "}",
    "if(d.type==='ve:export'){",
    "exportHtml((d.payload&&d.payload.css)||'');",
    "}",
    "if(d.type==='ve:verify'){",
    "var items=(d.payload&&d.payload.items)||[],results=[];",
    "for(var j=0;j<items.length;j++){",
    "var it=items[j],vel=null,ok=false,reason='';",
    "try{vel=document.querySelector(it.selector)}catch(e){}",
    "if(!vel){reason='目标已不存在';}",
    "else if(vel.tagName.toLowerCase()!==(it.tag||'')){reason='元素类型已变化';}",
    "else if(!it.skipDetail&&vel.childElementCount!==(it.childCount|0)){reason='结构已变化';}",
    "else if(!it.skipDetail&&((vel.textContent||'').replace(/\\s+/g,' ').trim().slice(0,40))!==(it.text||'')){reason='内容已变化';}",
    "else ok=true;",
    "results.push({id:it.id,ok:ok,reason:reason});",
    "}",
    "send('ve:verify:result',{results:results});",
    "}",
    "});",
    "function ready(){",
    "var pages=[];",
    "var secs=document.querySelectorAll('[data-page]');",
    "for(var i=0;i<secs.length;i++){var s=secs[i];",
    "pages.push({n:s.getAttribute('data-page')||String(i+1),title:s.getAttribute('data-title')||'',component:s.getAttribute('data-component')||''});}",
    "send('ve:ready',{pages:pages,title:document.title||''});",
    "}",
    "if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();",
    "})();",
  ].join("\n");
}

export function injectAgent(html: string, channel: string): string {
  const script = `<script data-ve-agent="1">${buildPickAgentScript(channel)}</script>`;
  if (/<\/body>/i.test(html)) return html.replace(/<\/body>/i, `${script}</body>`);
  return html + script;
}
