/**
 * V2-lite Visual Object Engine 的 iframe 内代理脚本。
 * 随 srcdoc 注入课件 HTML（sandbox 无 allow-same-origin，Host 只能靠 postMessage）。
 * 非破坏：不修改课件元素样式；冻结/悬停框均为运行时注入并退出时移除。
 */
export function buildPickAgentScript(channel: string): string {
  const ch = JSON.stringify(channel);
  return [
    "(function(){",
    "if(window.__veAgent)return;window.__veAgent=true;",
    `var CH=${ch};`,
    "function send(t,p){try{parent.postMessage({ve:1,ch:CH,type:t,payload:p||{}},'*')}catch(e){}}",
    "var pickOn=false,curSel=null,hoverBox=null,freezeEl=null;",
    "function ensureHover(){",
    "if(hoverBox)return;",
    "hoverBox=document.createElement('div');",
    "hoverBox.setAttribute('data-ve-ui','hover');",
    "hoverBox.style.cssText='position:fixed;pointer-events:none;z-index:2147483646;border:1.5px dashed #2563eb;background:rgba(37,99,235,.06);display:none';",
    "document.documentElement.appendChild(hoverBox);",
    "}",
    "function setFreeze(on){",
    "if(on&&!freezeEl){freezeEl=document.createElement('style');freezeEl.id='ve-freeze';",
    "freezeEl.textContent='*,*::before,*::after{animation-play-state:paused !important;transition:none !important}';",
    "(document.head||document.documentElement).appendChild(freezeEl);}",
    "if(!on&&freezeEl){freezeEl.parentNode.removeChild(freezeEl);freezeEl=null;}",
    "}",
    "function cssPath(el){",
    "if(!el||el.nodeType!==1)return '';",
    "if(el===document.documentElement)return 'html';",
    "if(el===document.body)return 'body';",
    "var parts=[],e=el,depth=0;",
    "while(e&&e.nodeType===1&&depth<9){",
    "var s=e.tagName.toLowerCase();",
    "var n=1,p=e.previousElementSibling;",
    "while(p){if(p.tagName===e.tagName)n++;p=p.previousElementSibling;}",
    "if(n>1)s+=':nth-of-type('+n+')';",
    "parts.unshift(s);",
    "if(e===document.body)break;",
    "e=e.parentElement;depth++;",
    "}",
    "return parts.join(' > ');",
    "}",
    "function info(el){",
    "var r=el.getBoundingClientRect(),cs=getComputedStyle(el);",
    "var chain=[],e=el;",
    "while(e&&e.nodeType===1&&chain.length<9){",
    "chain.unshift({tag:e.tagName.toLowerCase(),component:(e.getAttribute&&e.getAttribute('data-component'))||'',selector:cssPath(e)});",
    "e=e.parentElement;}",
    "return {",
    "tag:el.tagName.toLowerCase(),",
    "id:el.id||'',",
    "cls:(el.getAttribute('class')||'').slice(0,140),",
    "component:el.getAttribute('data-component')||'',",
    "page:el.getAttribute('data-page')||'',",
    "pageTitle:el.getAttribute('data-title')||'',",
    "selector:cssPath(el),",
    "rect:{x:r.left,y:r.top,w:r.width,h:r.height},",
    "text:(el.innerText||'').replace(/\\s+/g,' ').slice(0,120),",
    "styles:{display:cs.display,fontSize:cs.fontSize,fontWeight:cs.fontWeight,fontFamily:String(cs.fontFamily).slice(0,60),color:cs.color,background:cs.backgroundColor,textAlign:cs.textAlign,lineHeight:cs.lineHeight,margin:cs.margin,padding:cs.padding},",
    "chain:chain",
    "};",
    "}",
    "function select(el){curSel=el;send('ve:pick',info(el));}",
    "document.addEventListener('click',function(ev){",
    "if(!pickOn)return;",
    "ev.preventDefault();ev.stopPropagation();",
    "var el=ev.target;",
    "if(!el||el.nodeType!==1)return;",
    "select(el);",
    "},true);",
    "document.addEventListener('mouseover',function(ev){",
    "if(!pickOn)return;",
    "var el=ev.target;",
    "if(!el||el.nodeType!==1||el===hoverBox)return;",
    "ensureHover();",
    "var r=el.getBoundingClientRect();",
    "hoverBox.style.display='block';",
    "hoverBox.style.left=r.left+'px';hoverBox.style.top=r.top+'px';",
    "hoverBox.style.width=r.width+'px';hoverBox.style.height=r.height+'px';",
    "},true);",
    "document.addEventListener('mouseout',function(ev){",
    "if(hoverBox&&ev.target!==hoverBox)hoverBox.style.display='none';",
    "},true);",
    "var scrollTimer=0;",
    "function onScrollResize(){",
    "if(!curSel)return;",
    "clearTimeout(scrollTimer);",
    "scrollTimer=setTimeout(function(){",
    "var r=curSel.getBoundingClientRect();",
    "send('ve:rect',{rect:{x:r.left,y:r.top,w:r.width,h:r.height}});",
    "},80);",
    "}",
    "window.addEventListener('scroll',onScrollResize,true);",
    "window.addEventListener('resize',onScrollResize);",
    "window.addEventListener('message',function(ev){",
    "var d=ev.data;",
    "if(!d||d.ve!==1||d.ch!==CH)return;",
    "if(d.type==='ve:pick:set'){",
    "pickOn=!!(d.payload&&d.payload.enabled);",
    "setFreeze(pickOn);",
    "if(!pickOn&&hoverBox)hoverBox.style.display='none';",
    "send('ve:pick:mode',{enabled:pickOn});",
    "}",
    "if(d.type==='ve:pick:goto'){",
    "var el=null;",
    "try{el=document.querySelector((d.payload&&d.payload.selector)||'')}catch(e){}",
    "if(el)select(el);",
    "}",
    "});",
    "function ready(){",
    "var pages=[];",
    "var secs=document.querySelectorAll('[data-page]');",
    "for(var i=0;i<secs.length;i++){var s=secs[i];",
    "pages.push({n:s.getAttribute('data-page')||String(i+1),title:s.getAttribute('data-title')||'',component:s.getAttribute('data-component')||''});}",
    "send('ve:ready',{pages:pages,title:document.title||''});",
    "}",
    "if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();",
    "})();",
  ].join("\n");
}

export function injectAgent(html: string, channel: string): string {
  const script = `<script data-ve-agent="1">${buildPickAgentScript(channel)}</script>`;
  if (/<\/body>/i.test(html)) return html.replace(/<\/body>/i, `${script}</body>`);
  return html + script;
}
